In [69]:
import pandas as pd
from datetime import date, datetime
import copy

In [25]:
!pip install --upgrade pandas

Requirement already satisfied: pandas in /Applications/anaconda3/lib/python3.9/site-packages (1.4.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /Applications/anaconda3/lib/python3.9/site-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.18.5 in /Applications/anaconda3/lib/python3.9/site-packages (from pandas) (1.20.3)
Requirement already satisfied: pytz>=2020.1 in /Applications/anaconda3/lib/python3.9/site-packages (from pandas) (2021.3)
Requirement already satisfied: six>=1.5 in /Applications/anaconda3/lib/python3.9/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [26]:
df = pd.DataFrame([["ABC", "XYZ"]], columns=["Foo", "Bar"])

In [27]:
df.head()

   Foo  Bar
0  ABC  XYZ

In [28]:
df2 = pd.DataFrame([["ABC", "XYZ"], ["DEF", "UVW"]], columns=["Foo", "Bar"])

In [29]:
df2.head()

   Foo  Bar
0  ABC  XYZ
1  DEF  UVW

In [30]:
with pd.ExcelWriter("path_to_file.xlsx") as writer:
    df.to_excel(writer, sheet_name='Sheet1')
    df2.to_excel(writer, sheet_name='Sheet2')

In [31]:
df = pd.DataFrame(
    [
        [date(2014, 1, 31), date(1999, 9, 24)],
        [datetime(1998, 5, 26, 23, 33, 4), datetime(2014, 2, 28, 13, 5, 13)],
    ],
    index=['x', 'y'],
    columns=['Date', 'Datetime'],
)

In [32]:
df.head()

                 Date            Datetime
x 2014-01-31 00:00:00 1999-09-24 00:00:00
y 1998-05-26 23:33:04 2014-02-28 13:05:13

In [33]:
with pd.ExcelWriter(
    'path_to_file.xlsx', 
    date_format="YYYY-MM-DD",
    datetime_format="YYYY-MM-DD HH:MM:SS"
) as writer:
    df.to_excel(writer, sheet_name='Sheet3')

In [35]:
with pd.ExcelWriter(
    'path_to_file.xlsx', 
    mode='a', 
    engine="openpyxl", 
    if_sheet_exists="overlay",
) as writer:
    pd.DataFrame(
        [
            [1, 2],
            [3, 4]
        ],
        index=['x', 'y'],
        columns=['Date', 'Datetime'],
    ).to_excel(writer, sheet_name='Sheet3')

ValueError: 'overlay' is not valid for if_sheet_exists. Valid options are 'error', 'new' and 'replace'.

In [37]:
with pd.ExcelWriter("path_to_file.xlsx",
    mode="a",
    engine="openpyxl",
    if_sheet_exists="overlay",
) as writer:
    df.to_excel(writer, sheet_name="Sheet1")
    df2.to_excel(writer, sheet_name="Sheet1", startcol=3)

ValueError: 'overlay' is not valid for if_sheet_exists. Valid options are 'error', 'new' and 'replace'.

In [39]:
li = [x for x in range(10)]
li

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [42]:
with pd.ExcelWriter(
    'path_to_file.xlsx', 
) as writer:
    pd.DataFrame(
        [
            [x for x in range(10)],
            [x for x in range(11, 20)],
        ],
        index=[0, 1],
        columns=[x for x in range(10)],
    ).to_excel(writer, sheet_name='Test')

In [45]:
df = pd.DataFrame(
        [
            [x for x in range(10)],
            [x for x in range(10, 20)],
        ],
        index=[0, 1],
        columns=[x for x in range(10)],
    )
df.head()

    0   1   2   3   4   5   6   7   8   9
0   0   1   2   3   4   5   6   7   8   9
1  10  11  12  13  14  15  16  17  18  19

In [47]:
df.loc[2]=[x for x in range(10)]

In [48]:
df.head()

    0   1   2   3   4   5   6   7   8   9
0   0   1   2   3   4   5   6   7   8   9
1  10  11  12  13  14  15  16  17  18  19
2   0   1   2   3   4   5   6   7   8   9

In [49]:
df.index

Int64Index([0, 1, 2], dtype='int64')

In [50]:
len(df.index)

3

In [51]:
df.loc[len(df.index)] = [x for x in range(10)]

In [52]:
df.head()

    0   1   2   3   4   5   6   7   8   9
0   0   1   2   3   4   5   6   7   8   9
1  10  11  12  13  14  15  16  17  18  19
2   0   1   2   3   4   5   6   7   8   9
3   0   1   2   3   4   5   6   7   8   9

In [54]:
df2 = pd.DataFrame(
    [],
    index=[],
    columns=['a', 'b'],
)
df2

Empty DataFrame
Columns: [a, b]
Index: []

In [55]:
df2.loc[len(df2.index)] = [1, 2]

In [56]:
df2

   a  b
0  1  2

In [57]:
df2.columns

Index(['a', 'b'], dtype='object')

In [59]:
[x for x in df2.columns]

['a', 'b']

In [60]:
dict = {x: 1 for x in range(10)}

In [61]:
dict

{0: 1, 1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 1}

In [64]:
[v for k, v in dict.items()]

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [65]:
dict.items()

dict_items([(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 1), (8, 1), (9, 1)])

In [66]:
dict.values()

dict_values([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [67]:
[x for x in dict.values()]

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [72]:
df = pd.read_excel('Naive_S_P500.xlsx', sheet_name='return')
ret = copy.deepcopy(df.drop(columns=['Unnamed: 0']))
ret = ret.iloc[:, 1:397]
ret.head()

,AMAZON.COM,ABBOTT LABORATORIES,AES,ABIOMED,INTERNATIONAL BUS.MCHS.,ADVANCED MICRO DEVC.,ADOBE SYSTEMS,ALEXANDRIA RLST.EQTIES.,AIR PRDS.& CHEMS.,ALASKA AIR GROUP,...,DENTSPLY SIRONA,S&P GLOBAL,WELLTOWER,XEROX,HP,DXC TECHNOLOGY,WEC ENERGY GROUP,L3 TECHNOLOGIES,MONSTER BEVERAGE,SBA COMMS.
0,0.009078,0.003038,0.023104,0.011834,-0.001705,0.057158,0.041341,0.022843,0.007071,-0.013245,...,0.006313,0.003673,0.018993,0.017592,0.004881,0.010801,0.021277,0.013493,0.050852,0.028636
1,-0.006960,0.001515,0.041710,0.028468,-0.001341,0.004926,-0.002599,0.003878,-0.011472,0.019664,...,0.009212,-0.003673,0.010652,-0.001342,0.028774,-0.007253,0.003253,0.006480,-0.006679,0.016155
2,0.008430,0.012797,-0.009518,-0.007303,0.006689,0.033820,-0.009152,0.012739,-0.008692,-0.010908,...,-0.011435,-0.000969,0.020409,-0.010803,-0.007114,0.075583,-0.004005,-0.006879,-0.011340,0.000000
3,0.004606,0.019009,0.016010,0.020726,0.029265,0.002965,0.024135,0.011399,0.023012,-0.008472,...,0.015461,0.016726,0.004200,-0.006131,0.028166,0.006547,0.007496,0.011746,0.050511,0.000534
4,-0.016641,0.036495,-0.017206,0.040206,-0.014466,-0.015814,-0.016023,0.012903,-0.012794,0.016036,...,0.009815,-0.017308,0.014149,0.013571,0.012493,-0.008557,0.004471,0.009401,0.050881,0.006386

In [74]:
[x for x in ret.columns]

['AMAZON.COM',
 'ABBOTT LABORATORIES',
 'AES',
 'ABIOMED',
 'INTERNATIONAL BUS.MCHS.',
 'ADVANCED MICRO DEVC.',
 'ADOBE SYSTEMS',
 'ALEXANDRIA RLST.EQTIES.',
 'AIR PRDS.& CHEMS.',
 'ALASKA AIR GROUP',
 'BOSTON PROPERTIES',
 'ALLSTATE',
 'HONEYWELL INTL.',
 'AMGEN',
 'HESS',
 'AMERICAN EXPRESS',
 'AMER.ELEC.PWR.',
 'AFLAC',
 'AMERICAN INTL.GP.',
 'ANALOG DEVICES',
 'ANADARKO PETROLEUM',
 'ALEXION PHARMS.',
 'VALERO ENERGY',
 'APACHE',
 "COMCAST 'A'",
 'ANSYS',
 'APPLE',
 'APPLIED MATS.',
 'ALBEMARLE',
 'ARCHER-DANLS.-MIDL.',
 'PINNACLE WEST CAP.',
 'AMEREN',
 "APARTMENT INV.& MAN.'A'",
 'AUTODESK',
 'AUTOMATIC DATA PROC.',
 'AUTOZONE',
 'AVERY DENNISON',
 'BALL',
 "BERKSHIRE HATHAWAY 'B'",
 'BAXTER INTL.',
 'BECTON DICKINSON',
 'AMETEK',
 'VERIZON COMMUNICATIONS',
 'BEST BUY',
 'SL GREEN REALTY',
 'YUM! BRANDS',
 'FIRSTENERGY',
 'H&R BLOCK',
 'BOEING',
 'ROBERT HALF INTL.',
 'BORGWARNER',
 'BOSTON SCIENTIFIC',
 'CH ROBINSON WWD.',
 'TAKE TWO INTACT.SFTW.',
 'METTLER TOLEDO INTL.',
 'BRISTOL MYERS SQUIBB',
 'AFFILIATED MANAGERS',
 'ONEOK',
 'AVALONBAY COMMNS.',
 'UNITED RENTALS',
 'SEMPRA EN.',
 'FEDEX',
 'VERISIGN',
 "AMPHENOL 'A'",
 "BROWN-FORMAN 'B'",
 'QUANTA SERVICES',
 'CSX',
 "CABOT OIL & GAS 'A'",
 'CAMPBELL SOUP',
 "CONSTELLATION BRANDS 'A'",
 'CARDINAL HEALTH',
 'CATERPILLAR',
 'CELGENE',
 'CITRIX SYS.',
 'CENTURYLINK',
 'CERNER',
 'JP MORGAN CHASE & CO.',
 'CHURCH & DWIGHT CO.',
 'CIGNA',
 'CINCINNATI FINL.',
 'CINTAS',
 'CISCO SYSTEMS',
 'CLOROX',
 'COCA COLA',
 'COLGATE-PALM.',
 "MARRIOTT INTL.'A'",
 'COMERICA',
 'CA',
 'CONAGRA BRANDS',
 'CONSOLIDATED EDISON',
 'CMS ENERGY',
 'COOPER COS.',
 'CORNING',
 'SEALED AIR',
 'CUMMINS',
 'D R HORTON',
 'DANAHER',
 "MOODY'S",
 "COGNIZANT TECH.SLTN.'A'",
 'TARGET',
 'DEERE',
 'MORGAN STANLEY',
 "REPUBLIC SVS.'A'",
 'WALT DISNEY',
 'DOLLAR TREE',
 'DOVER',
 'OMNICOM GROUP',
 'DTE ENERGY',
 'DUKE REALTY',
 'FLOWSERVE',
 'DARDEN RESTAURANTS',
 'EBAY',
 'BANK OF AMERICA',
 'CITIGROUP',
 'EASTMAN CHEMICAL',
 'E*TRADE FINANCIAL',
 'CADENCE DESIGN SYS.',
 "DISH NETWORK 'A'",
 'ECOLAB',
 'PERKINELMER',
 'ELECTRONIC ARTS',
 'EMERSON ELECTRIC',
 'ESSEX PROPERTY TST.',
 'ENTERGY',
 'EOG RES.',
 'EQUIFAX',
 'EQUITY RESD.TST.PROPS. SHBI',
 'EQT',
 "ESTEE LAUDER COS.'A'",
 'EXPEDITOR INTL.OF WASH.',
 'EXXON MOBIL',
 'FMC',
 'NEXTERA ENERGY',
 'FASTENAL',
 'FEDERAL REALTY INV.TST.',
 'FIFTH THIRD BANCORP',
 'M&T BANK',
 'FISERV',
 'FLIR SYSTEMS',
 "MACY'S",
 'FRANKLIN RESOURCES',
 'FREEPORT-MCMORAN',
 'ARTHUR J GALLAGHER',
 'GAP',
 'GENERAL DYNAMICS',
 'GENERAL MILLS',
 'GENUINE PARTS',
 'GILEAD SCIENCES',
 "GARTNER 'A'",
 'GOODYEAR TIRE & RUB.',
 'MCKESSON',
 'NVIDIA',
 'GENERAL ELECTRIC',
 'WW GRAINGER',
 'HALLIBURTON',
 'GOLDMAN SACHS GP.',
 'HARLEY-DAVIDSON',
 'HARRIS',
 'HASBRO',
 'HENRY SCHEIN',
 'HCP',
 'HELMERICH & PAYNE',
 'HERSHEY',
 'F5 NETWORKS',
 'JUNIPER NETWORKS',
 'HOLOGIC',
 'UNUM GROUP',
 'HOME DEPOT',
 'HORMEL FOODS',
 'CENTERPOINT EN.',
 'HUMANA',
 'HUNT JB TRANSPORT SVS.',
 'HUNTINGTON BCSH.',
 'RED HAT',
 'NEKTAR THERAPEUTICS',
 'BIOGEN',
 'ILLINOIS TOOL WORKS',
 'INTUIT',
 'IDEXX LABORATORIES',
 'INTEL',
 'INTL.FLAVORS & FRAG.',
 'INTERNATIONAL PAPER',
 'INTERPUBLIC GROUP',
 'JACOBS ENGR.',
 'INCYTE',
 'JOHNSON & JOHNSON',
 'HARTFORD FINL.SVS.GP.',
 'KLA TENCOR',
 'DEVON ENERGY',
 'KELLOGG',
 'KEYCORP',
 'KIMCO REALTY',
 'KIMBERLY-CLARK',
 'BLACKROCK',
 "KOHL'S",
 'KROGER',
 'LAM RESEARCH',
 'AKAMAI TECHS.',
 'LEGGETT&PLATT',
 "LENNAR 'A'",
 'ELI LILLY',
 'LINCOLN NATIONAL',
 "UNITED PARCEL SER.'B'",
 'AGILENT TECHS.',
 'LOCKHEED MARTIN',
 'LOEWS',
 'CARNIVAL',
 "LOWE'S COMPANIES",
 'DOMINION ENERGY',
 'MACERICH',
 'SCANA',
 'MGM RESORTS INTL.',
 'MCCORMICK & COMPANY NV.',
 'MCDONALDS',
 'EVEREST RE GP.',
 'HOST HOTELS & RESORTS',
 'MARSH & MCLENNAN',
 'MASCO',
 'MARTIN MRTA.MATS.',
 'MATTEL',
 'ACTIVISION BLIZZARD',
 'CVS HEALTH',
 'LABORATORY CORP.OF AM. HDG.',
 'MICROSOFT',
 'MICRON TECHNOLOGY',
 'MID-AMER.APT COMMUNITIES',
 'MICROCHIP TECH.',
 '3M',
 'MOHAWK INDUSTRIES',
 'KANSAS CITY SOUTHERN',
 'XCEL ENERGY',
 'FORD MOTOR',
 'NATIONAL OILWELL VARCO',
 'NETAPP',
 'NEWFIELD EXPLORATION',
 'NEWELL BRANDS',
 'NEWMONT MINING',
 "NIKE 'B'",
 'NOBLE ENERGY',
 'NORDSTROM',
 'NORFOLK SOUTHERN',
 'NISOURCE',
 'NORTHERN TRUST',
 'NORTHROP GRUMMAN',
 'WELLS FARGO & CO',
 'NUCOR',
 'CAPITAL ONE FINL.',
 'OCCIDENTAL PTL.',
 'ORACLE',
 'PACCAR',
 'EXELON',
 'PARKER-HANNIFIN',
 'PAYCHEX',
 'PPL',
 'PEPSICO',
 'PFIZER',
 'CONOCOPHILLIPS',
 'PG&E',
 'PIONEER NTRL.RES.',
 'ALTRIA GROUP',
 'PNC FINL.SVS.GP.',
 'AETNA',
 'PPG INDUSTRIES',
 'PRAXAIR',
 'COSTCO WHOLESALE',
 'T ROWE PRICE GROUP',
 'QUEST DIAGNOSTICS',
 'PROCTER & GAMBLE',
 'PROGRESSIVE OHIO',
 'PUB.SER.ENTER.GP.',
 'PULTEGROUP',
 'QUALCOMM',
 'RAYMOND JAMES FINL.',
 'REALTY INCOME',
 'REGENCY CENTERS',
 'UDR',
 'REGENERON PHARMS.',
 'RESMED',
 'US BANCORP',
 'ROSS STORES',
 'ROPER TECHNOLOGIES',
 'ROCKWELL AUTOMATION',
 'ROYAL CARIBBEAN CRUISES',
 "RAYTHEON 'B'",
 'TRAVELERS COS.',
 'MERCK & COMPANY',
 'SCHLUMBERGER',
 'CHARLES SCHWAB',
 'AMERISOURCEBERGEN',
 'SHERWIN-WILLIAMS',
 'SVB FINANCIAL GROUP',
 'SIMON PROPERTY GROUP',
 'SMITH (AO)',
 'SNAP-ON',
 'EDISON INTL.',
 'SOUTHERN',
 'BB&T',
 'SOUTHWEST AIRLINES',
 'AT&T',
 'CHEVRON',
 'STATE STREET',
 'STARBUCKS',
 'PUBLIC STORAGE',
 'STRYKER',
 'STERICYCLE',
 'SUNTRUST BANKS',
 'SYMANTEC',
 'SYNOPSYS',
 'SYSCO',
 'TEXAS INSTRUMENTS',
 'TEXTRON',
 'THERMO FISHER SCIENTIFIC',
 'TIFFANY & CO',
 'TORCHMARK',
 'TOTAL SYSTEM SERVICES',
 'DAVITA',
 'TRACTOR SUPPLY',
 "TYSON FOODS 'A'",
 'MARATHON OIL',
 'UNION PACIFIC',
 'UNITED TECHNOLOGIES',
 'UNITEDHEALTH GROUP',
 "UNIVERSAL HEALTH SVS.'B'",
 'VARIAN MEDICAL SYSTEMS',
 'VENTAS',
 'V F',
 'VERTEX PHARMS.',
 'VULCAN MATERIALS',
 'VORNADO REALTY TRUST',
 'WALMART',
 'WASTE MANAGEMENT',
 'WATERS',
 'J M SMUCKER',
 'WESTERN DIGITAL',
 'WEYERHAEUSER',
 'WHIRLPOOL',
 'SKYWORKS SOLUTIONS',
 'WILLIAMS',
 'ALLIANT ENERGY CORP.',
 'FOOT LOCKER',
 'CARMAX',
 'XILINX',
 'TJX',
 'ZIONS BANCORP.',
 'REGIONS FINL.NEW',
 "MOLSON COORS BREWING 'B'",
 "VIACOM 'B'",
 "CBS 'B'",
 'PEOPLES UNITED FINANCIAL',
 'BANK OF NEW YORK MELLON',
 'CHUBB',
 'MOSAIC',
 'STANLEY BLACK & DECKER',
 'PVH',
 'PROLOGIS',
 'RALPH LAUREN CL.A',
 'MOTOROLA SOLUTIONS',
 'AON CLASS A',
 'HOLLYFRONTIER',
 'INGERSOLL-RAND',
 'O REILLY AUTOMOTIVE',
 'AMERICAN TOWER',
 'EXPRESS SCRIPTS HOLDING',
 'DUKE ENERGY',
 'EATON',
 'L BRANDS',
 'ARCONIC',
 'ENVISION HEALTHCARE',
 'XL GROUP',
 'BAKER HUGHES A',
 'BOOKING HOLDINGS',
 'ANDEAVOR',
 'EVERGY',
 'JEFFERIES FINANCIAL GROUP',
 'PERRIGO',
 'PENTAIR',
 'QORVO',
 'CROWN CASTLE INTL.',
 'MEDTRONIC',
 'WALGREENS BOOTS ALLIANCE',
 'MYLAN',
 'IRON MOUNTAIN',
 'EVERSOURCE ENERGY',
 'JOHNSON CONTROLS INTL.',
 'ALLERGAN',
 'GGP',
 'DENTSPLY SIRONA',
 'S&P GLOBAL',
 'WELLTOWER',
 'XEROX',
 'HP',
 'DXC TECHNOLOGY',
 'WEC ENERGY GROUP',
 'L3 TECHNOLOGIES',
 'MONSTER BEVERAGE',
 'SBA COMMS.']

In [75]:
df = pd.DataFrame(
    [],
    index=[],
    columns=[x for x in ret.columns],
)
df

Empty DataFrame
Columns: [AMAZON.COM, ABBOTT LABORATORIES, AES, ABIOMED, INTERNATIONAL BUS.MCHS., ADVANCED MICRO DEVC., ADOBE SYSTEMS, ALEXANDRIA RLST.EQTIES., AIR PRDS.& CHEMS., ALASKA AIR GROUP, BOSTON PROPERTIES, ALLSTATE, HONEYWELL INTL., AMGEN, HESS, AMERICAN EXPRESS, AMER.ELEC.PWR., AFLAC, AMERICAN INTL.GP., ANALOG DEVICES, ANADARKO PETROLEUM, ALEXION PHARMS., VALERO ENERGY, APACHE, COMCAST 'A', ANSYS, APPLE, APPLIED MATS., ALBEMARLE, ARCHER-DANLS.-MIDL., PINNACLE WEST CAP., AMEREN, APARTMENT INV.& MAN.'A', AUTODESK, AUTOMATIC DATA PROC., AUTOZONE, AVERY DENNISON, BALL, BERKSHIRE HATHAWAY 'B', BAXTER INTL., BECTON DICKINSON, AMETEK, VERIZON COMMUNICATIONS, BEST BUY, SL GREEN REALTY, YUM! BRANDS, FIRSTENERGY, H&R BLOCK, BOEING, ROBERT HALF INTL., BORGWARNER, BOSTON SCIENTIFIC, CH ROBINSON WWD., TAKE TWO INTACT.SFTW., METTLER TOLEDO INTL., BRISTOL MYERS SQUIBB, AFFILIATED MANAGERS, ONEOK, AVALONBAY COMMNS., UNITED RENTALS, SEMPRA EN., FEDEX, VERISIGN, AMPHENOL 'A', BROWN-FORMAN 'B', QUANTA SERVICES, CSX, CABOT OIL & GAS 'A', CAMPBELL SOUP, CONSTELLATION BRANDS 'A', CARDINAL HEALTH, CATERPILLAR, CELGENE, CITRIX SYS., CENTURYLINK, CERNER, JP MORGAN CHASE & CO., CHURCH & DWIGHT CO., CIGNA, CINCINNATI FINL., CINTAS, CISCO SYSTEMS, CLOROX, COCA COLA, COLGATE-PALM., MARRIOTT INTL.'A', COMERICA, CA, CONAGRA BRANDS, CONSOLIDATED EDISON, CMS ENERGY, COOPER COS., CORNING, SEALED AIR, CUMMINS, D R HORTON, DANAHER, MOODY'S, COGNIZANT TECH.SLTN.'A', TARGET, ...]
Index: []

[0 rows x 396 columns]

In [76]:
df.loc[len(df.index)] = [x for x in range(396)]
df.head()

,AMAZON.COM,ABBOTT LABORATORIES,AES,ABIOMED,INTERNATIONAL BUS.MCHS.,ADVANCED MICRO DEVC.,ADOBE SYSTEMS,ALEXANDRIA RLST.EQTIES.,AIR PRDS.& CHEMS.,ALASKA AIR GROUP,...,DENTSPLY SIRONA,S&P GLOBAL,WELLTOWER,XEROX,HP,DXC TECHNOLOGY,WEC ENERGY GROUP,L3 TECHNOLOGIES,MONSTER BEVERAGE,SBA COMMS.
0,0,1,2,3,4,5,6,7,8,9,...,386,387,388,389,390,391,392,393,394,395

In [78]:
with pd.ExcelWriter('test.xlsx') as writer:
    df.to_excel(writer, sheet_name='testing_sheet')

In [79]:
li = [1, 2, 3]
li2 = [-1, 0, 1]
[x + y for x, y in zip(li, li2)]

[0, 2, 4]

In [80]:
df.head()

,AMAZON.COM,ABBOTT LABORATORIES,AES,ABIOMED,INTERNATIONAL BUS.MCHS.,ADVANCED MICRO DEVC.,ADOBE SYSTEMS,ALEXANDRIA RLST.EQTIES.,AIR PRDS.& CHEMS.,ALASKA AIR GROUP,...,DENTSPLY SIRONA,S&P GLOBAL,WELLTOWER,XEROX,HP,DXC TECHNOLOGY,WEC ENERGY GROUP,L3 TECHNOLOGIES,MONSTER BEVERAGE,SBA COMMS.
0,0,1,2,3,4,5,6,7,8,9,...,386,387,388,389,390,391,392,393,394,395

In [81]:
df.loc[len(df.index)] = [x for x in range(396)]

In [83]:
df.head()

,AMAZON.COM,ABBOTT LABORATORIES,AES,ABIOMED,INTERNATIONAL BUS.MCHS.,ADVANCED MICRO DEVC.,ADOBE SYSTEMS,ALEXANDRIA RLST.EQTIES.,AIR PRDS.& CHEMS.,ALASKA AIR GROUP,...,DENTSPLY SIRONA,S&P GLOBAL,WELLTOWER,XEROX,HP,DXC TECHNOLOGY,WEC ENERGY GROUP,L3 TECHNOLOGIES,MONSTER BEVERAGE,SBA COMMS.
0,0,1,2,3,4,5,6,7,8,9,...,386,387,388,389,390,391,392,393,394,395
1,0,1,2,3,4,5,6,7,8,9,...,386,387,388,389,390,391,392,393,394,395

In [85]:
[x + y for x, y in zip(df.loc[0], df.loc[1])]

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,
 352,
 354,
 356,
 358,
 360,
 362,
 364,
 366,
 368,
 370,
 372,
 374,
 376,
 378,
 380,
 382,
 384,
 386,
 388,
 390,
 392,
 394,
 396,
 398,
 400,
 402,
 404,
 406,
 408,
 410,
 412,
 414,
 416,
 418,
 420,
 422,
 424,
 426,
 428,
 430,
 432,
 434,
 436,
 438,
 440,
 442,
 444,
 446,
 448,
 450,
 452,
 454,
 456,
 458,
 460,
 462,
 464,
 466,
 468,
 470,
 472,
 474,
 476,
 478,
 480,
 482,
 484,
 486,
 488,
 490,
 492,
 494,
 496,
 498,
 500,
 502,
 504,
 506,
 508,
 510,
 512,
 514,
 516,
 518,
 520,
 522,
 524,
 526,
 528,
 530,
 532,
 534,
 536,
 538,
 540,
 542,
 544,
 546,
 548,
 550,
 552,
 554,
 556,
 558,
 560,
 562,
 564,
 566,
 568,
 570,
 572,
 574,
 576,
 578,
 580,
 582,
 584,
 586,
 588,
 590,
 592,
 594,
 596,
 598,
 600,
 602,
 604,
 606,
 608,
 610,
 612,
 614,
 616,
 618,
 620,
 622,
 624,
 626,
 628,
 630,
 632,
 634,
 636,
 638,
 640,
 642,
 644,
 646,
 648,
 650,
 652,
 654,
 656,
 658,
 660,
 662,
 664,
 666,
 668,
 670,
 672,
 674,
 676,
 678,
 680,
 682,
 684,
 686,
 688,
 690,
 692,
 694,
 696,
 698,
 700,
 702,
 704,
 706,
 708,
 710,
 712,
 714,
 716,
 718,
 720,
 722,
 724,
 726,
 728,
 730,
 732,
 734,
 736,
 738,
 740,
 742,
 744,
 746,
 748,
 750,
 752,
 754,
 756,
 758,
 760,
 762,
 764,
 766,
 768,
 770,
 772,
 774,
 776,
 778,
 780,
 782,
 784,
 786,
 788,
 790]

In [87]:
df.iloc[-1]

AMAZON.COM                   0
ABBOTT LABORATORIES          1
AES                          2
ABIOMED                      3
INTERNATIONAL BUS.MCHS.      4
                          ...
DXC TECHNOLOGY             391
WEC ENERGY GROUP           392
L3 TECHNOLOGIES            393
MONSTER BEVERAGE           394
SBA COMMS.                 395
Name: 1, Length: 396, dtype: object

In [88]:
df.iloc[-2]

AMAZON.COM                   0
ABBOTT LABORATORIES          1
AES                          2
ABIOMED                      3
INTERNATIONAL BUS.MCHS.      4
                          ...
DXC TECHNOLOGY             391
WEC ENERGY GROUP           392
L3 TECHNOLOGIES            393
MONSTER BEVERAGE           394
SBA COMMS.                 395
Name: 0, Length: 396, dtype: object

In [197]:
df = pd.read_excel('Naive_S_P500.xlsx', sheet_name='return')
ret = copy.deepcopy(df.drop(columns=['Unnamed: 0']))
ret = ret.iloc[:, 1:397]
ret.shape

(3234, 396)

In [198]:
(3234-60) // 20

158

In [90]:
ret.head()

,AMAZON.COM,ABBOTT LABORATORIES,AES,ABIOMED,INTERNATIONAL BUS.MCHS.,ADVANCED MICRO DEVC.,ADOBE SYSTEMS,ALEXANDRIA RLST.EQTIES.,AIR PRDS.& CHEMS.,ALASKA AIR GROUP,...,DENTSPLY SIRONA,S&P GLOBAL,WELLTOWER,XEROX,HP,DXC TECHNOLOGY,WEC ENERGY GROUP,L3 TECHNOLOGIES,MONSTER BEVERAGE,SBA COMMS.
0,0.009078,0.003038,0.023104,0.011834,-0.001705,0.057158,0.041341,0.022843,0.007071,-0.013245,...,0.006313,0.003673,0.018993,0.017592,0.004881,0.010801,0.021277,0.013493,0.050852,0.028636
1,-0.006960,0.001515,0.041710,0.028468,-0.001341,0.004926,-0.002599,0.003878,-0.011472,0.019664,...,0.009212,-0.003673,0.010652,-0.001342,0.028774,-0.007253,0.003253,0.006480,-0.006679,0.016155
2,0.008430,0.012797,-0.009518,-0.007303,0.006689,0.033820,-0.009152,0.012739,-0.008692,-0.010908,...,-0.011435,-0.000969,0.020409,-0.010803,-0.007114,0.075583,-0.004005,-0.006879,-0.011340,0.000000
3,0.004606,0.019009,0.016010,0.020726,0.029265,0.002965,0.024135,0.011399,0.023012,-0.008472,...,0.015461,0.016726,0.004200,-0.006131,0.028166,0.006547,0.007496,0.011746,0.050511,0.000534
4,-0.016641,0.036495,-0.017206,0.040206,-0.014466,-0.015814,-0.016023,0.012903,-0.012794,0.016036,...,0.009815,-0.017308,0.014149,0.013571,0.012493,-0.008557,0.004471,0.009401,0.050881,0.006386

In [94]:
[x for x in ret.iloc[0, 1:397]]

[0.0030378591124276396,
 0.023104368345417656,
 0.011834457647002798,
 -0.0017046150480942365,
 0.05715841383994862,
 0.041341340156441544,
 0.022842697735070982,
 0.007070925068173204,
 -0.013245226750020567,
 0.01645632159947934,
 0.012132501761913266,
 0.00562162245535101,
 0.018842411497252506,
 0.05230606870532131,
 0.021531012448137054,
 0.007253221859142324,
 0.0032261561479949297,
 0.020167928576437743,
 0.022875463516333454,
 0.02758436668595379,
 0.00197336028517529,
 0.052107324247496714,
 0.03414476008216274,
 0.011885109958923905,
 -0.07538813965183132,
 0.039014714856720645,
 0.021506205220963463,
 0.06608556374551441,
 -0.011419373683072834,
 0.02625449128765599,
 0.012027303081984735,
 0.022196150706826186,
 -0.00420168685369997,
 0.0093262514995076,
 0.010948025452651302,
 0.01899698706145096,
 0.012260881732210937,
 0.009999235927585079,
 0.01868163046528485,
 0.006139569604922358,
 -0.0004682000966380665,
 0.008595174722369092,
 0.02834335519174814,
 0.017003459820333373,
 -0.0027746190818830666,
 0.021006629849630122,
 -0.004081638319648619,
 0.002843334301144251,
 -0.010879767660288055,
 0.018466085632881303,
 -0.001225740705050014,
 0.007264931724248356,
 0.019581045199106563,
 0.007579895522769171,
 0.011250659563100876,
 0.026802686315010933,
 0.02557792496548737,
 0.024241598826806803,
 0.018216983331066333,
 0.028579654541648312,
 -0.0006772773709620183,
 -0.01564689078165874,
 0.004733469899701517,
 0.02816279997834598,
 0.015071875358661975,
 -0.016287063191233922,
 0.05373200346193549,
 0.007696206634470283,
 -0.009191945225383445,
 0.01701814044763324,
 0.0005191658851575032,
 0.001233806448928344,
 0.017594288001552567,
 -0.0015089787079392248,
 0.01159248149274299,
 0.012518941666135779,
 0.014427662346520738,
 0.005357160452444297,
 0.004911820547208571,
 0.008473601118993713,
 0.01909227793484011,
 0.0045598114782635524,
 0.014530485919681473,
 0.001093294569541894,
 0.00803265854426617,
 0.01469071541000381,
 -0.011057719233698091,
 0.011767583805597868,
 0.007954465246294673,
 0.00275292672140508,
 0.0,
 0.019643039033557744,
 -0.01434487570946566,
 0.012624752397289378,
 0.033304302735775476,
 0.010344497888669594,
 0.024764089096471365,
 0.007925541783334503,
 -0.004558308558274016,
 -0.0016163400771202789,
 0.027294592028118562,
 0.01847151362121042,
 0.01778079777725112,
 0.010806065255681065,
 0.02439540839959347,
 0.011446048812108292,
 0.012196676335728135,
 0.02979131982673414,
 0.03355594177126333,
 -0.010083818245378654,
 0.028287232580733932,
 0.019951321443214695,
 0.015539260181049952,
 0.013094737468271842,
 0.0038277595327012577,
 0.0017714796483817993,
 0.034001684402716274,
 -0.015840264509217643,
 0.018086718068217336,
 0.019498961371348458,
 0.005739854242297512,
 0.023792784555592427,
 0.026024040699111323,
 0.07355290078358662,
 0.01254590423345541,
 0.021995577692110444,
 0.02529736623815532,
 -0.004190368298626463,
 -0.0010374213601791631,
 0.04013099564323771,
 0.017154998367088593,
 0.011959004043526981,
 0.00025552574560896627,
 0.01602912958409269,
 0.003968784148446601,
 0.017633614516250094,
 0.009659688726550925,
 0.01687429026540071,
 0.028095493453035036,
 0.019904801335196832,
 0.048613126017247994,
 0.0147865117712994,
 0.003960401216096914,
 0.008295179632853093,
 0.005257848310900908,
 0.006581210636876662,
 0.039718094596578914,
 0.008490981156787359,
 0.027243455611107033,
 0.026964058295563188,
 0.04440145700015906,
 0.009088389736790202,
 0.00979713924498326,
 0.05311539062425625,
 0.00904207579212914,
 -0.004281828262440803,
 0.020027078874396094,
 -0.008959741371471869,
 0.0009161704717795821,
 0.01283155550348628,
 0.054075722539090224,
 -0.007266153676622919,
 0.07736248114566333,
 -0.051057306185865334,
 -0.036797491191033704,
 0.017429635135283596,
 0.018600634169549293,
 0.011258296305893109,
 0.01160554612030789,
 0.026338821635911287,
 0.003967384529469681,
 0.019183240469317027,
 0.0285682057003187,
 -0.001215805620889878,
 0.03173476184166908,
 0.017908909121684607,
 0.014528100562909808,
 0.005403546227151675,
 0.024145245801868415,
 0.0074349784875179905,
 -0.003576609846373169,
 0.008255980847019078,
 0.01665731091684344,
 0.0,
 0.025138923432989946,
 0.02495099254947435,
 0.02719623723861115,
 0.03380027802619881,
 0.011502312229597803,
 0.022223136784710256,
 0.02005930551477526,
 -0.0038624566526416085,
 0.004782058037058314,
 -0.025634413970787716,
 0.0037007708110806873,
 0.027913930655381926,
 0.04272685248256906,
 0.050530808647215965,
 0.028276185006006694,
 0.013514905136932312,
 0.009384453256251373,
 0.0053085725197649985,
 0.006288755890048835,
 -0.0012580596092377826,
 0.019624807711758594,
 0.020363532237500453,
 0.00613177723205213,
 0.02507166370363445,
 0.02631133286911127,
 0.019862375160211304,
 0.007065246781237087,
 0.009335332563466752,
 -0.005948857519772285,
 0.0045734818235029905,
 0.0120609325658737,
 0.003771217543079324,
 0.0332290704226209,
 0.025607781579176016,
 -0.020434938414306894,
 0.014451118538174506,
 -0.0026530241068078923,
 -0.0031619109389712965,
 0.02604412159254921,
 0.014914519565087075,
 0.03045920748470844,
 -0.0006222775558611619,
 0.020561352674003767,
 0.029677112811392382,
 0.0004092490337454726,
 0.0059411462899082,
 0.01414814596602698,
 0.07834806150657275,
 0.03314818154390181,
 0.04012672591479082,
 0.0029393260717144004,
 0.06769365083647787,
 -0.00972572087013021,
 0.026929411878631543,
 0.008519753344770486,
 -0.03126670645594702,
 0.02228225538273453,
 0.009411382248555821,
 -0.008018418021021082,
 0.01532052393588856,
 0.038805574421795073,
 0.006690531359482418,
 0.07347331833811574,
 0.03144152583481888,
 0.016045995556970487,
 0.02747017571389134,
 0.010406556780951376,
 0.013290097892188612,
 0.020204026897022158,
 0.01144408316138276,
 0.019533529780344207,
 0.03926684671828516,
 0.009384704887596318,
 0.031108499282279312,
 0.003474811140902239,
 0.02759565809803789,
 -0.0026543520388914903,
 0.0017256259674698574,
 0.016294020944113162,
 0.009055298821554968,
 0.013239746562269398,
 -0.0029180061557140414,
 0.01542975922748823,
 -0.010848147710875498,
 0.02507920787309412,
 0.04665858696470658,
 0.02113078163007332,
 0.021796845607291792,
 0.02647347666717137,
 0.025457747301741603,
 0.020688937211469985,
 0.0,
 -0.002352019900430689,
 0.01296345227340155,
 0.018512698742289075,
 0.001011889790363416,
 0.010927233213866789,
 -0.002221729418662748,
 -0.003742986278834392,
 0.029121846187805053,
 0.029122256320208276,
 0.061961864210842654,
 0.01957538039144099,
 0.020559957024179096,
 -0.005076713254224142,
 -0.006210535006440601,
 0.023217425499784474,
 0.04865991555720969,
 0.025497504298004126,
 0.0262517903981992,
 0.015517552750185657,
 0.009499002794996178,
 0.0,
 0.008943149036442472,
 0.03988444048054413,
 0.027398974188114347,
 0.028254179061792246,
 0.032542092885466695,
 0.003818942078201261,
 -0.004596143932283011,
 0.01730406280508543,
 -0.0005715918989577644,
 0.019743977989690988,
 0.001287415691174722,
 0.03583295628218401,
 0.00673228850370126,
 0.004966075427038164,
 0.012715884325302714,
 0.0035911177711175513,
 -0.016815682856615298,
 0.017228303960177566,
 0.011083047606334773,
 -0.023071120901311887,
 0.0676919278220557,
 -0.004481521256327373,
 0.01102821564864553,
 -0.006619867559096909,
 0.003417346341521768,
 -0.007378296079387153,
 0.02345850977345903,
 -0.005799218862351363,
 0.008277895028485376,
 0.01348796287277482,
 0.03032467288382753,
 -0.012254264923466936,
 0.010488460620652982,
 0.007905179507113468,
 0.03088184543343462,
 0.021791986463084917,
 0.00450905605406445,
 -0.013098787297697194,
 0.02330202520284411,
 0.031025326278987766,
 0.016272025108215443,
 -0.006805640899879385,
 0.031647085493212886,
 0.02197028346444511,
 -0.0034497662500747347,
 0.012102226109837046,
 0.009614058028380683,
 0.0023855684490704993,
 0.2435474653821584,
 0.0,
 0.007698174098357743,
 0.020510472564012436,
 0.02037484818905218,
 0.02497598607017699,
 0.0027024234303465906,
 -0.01555241300748477,
 0.011726782180753705,
 -0.006791804481468058,
 0.023622392933896192,
 0.03552286065851282,
 0.04451822959029262,
 0.0027210563820409452,
 -0.0006250000203450813,
 0.007352974305258733,
 0.03551917658451639,
 0.014108105786736597,
 0.002084574906148702,
 -0.0022396425935047983,
 0.011097428804078512,
 0.021208325748241733,
 0.01253611284892554,
 0.05052811132385833,
 0.01600034134644112,
 0.052843676002614595,
 0.005103235385177466,
 0.001895439829034928,
 0.016628251437578474,
 -0.0069739485738188915,
 0.0380825710472096,
 -0.0003716781310210809,
 0.004851854951967336,
 0.025210481845470704,
 0.0020020026706729687,
 -0.004035925582897722,
 0.0055710450494554295,
 0.02667039372013796,
 0.01313999043368031,
 0.027081034089000863,
 0.006312683421496327,
 0.0036732762424062045,
 0.01899253582727432,
 0.017591935803732025,
 0.004881053435975954,
 0.010801126900727976,
 0.02127739844728488,
 0.013493323400094496,
 0.05085162181204465,
 0.02863631798045155]

In [93]:
list(ret.iloc[1, 1:397])

[0.0015154758299004926,
 0.041710488581370456,
 0.02846792137701943,
 -0.001341381824201336,
 0.004926118336056003,
 -0.0025994295895142355,
 0.0038778526539788613,
 -0.01147195449834431,
 0.019663554908778063,
 0.0037086135221491815,
 -0.0010968922489187842,
 -0.004013757601219609,
 -0.004739936528061292,
 0.013233913034620294,
 -0.012054101756498624,
 -0.0016072867108720265,
 0.005567466201164447,
 0.0014348427625647034,
 0.009221654717453853,
 0.008892581725845956,
 0.0063866588987961884,
 0.010066708264346311,
 -0.002824860635554739,
 0.005702375088416977,
 -0.01501491498839286,
 0.002936145662470015,
 0.008690983547419812,
 -0.020217651166009067,
 0.06125174743094868,
 0.0028228670827045027,
 -0.0050261076230012375,
 0.00899852175882333,
 -0.00539464190902198,
 0.0032324166509752252,
 -0.009314483025689477,
 0.01480203236925745,
 0.043077593483304165,
 0.0006743088589960555,
 0.013725350573871038,
 0.014778594096118683,
 0.0105250415936663,
 0.028875763195417188,
 -0.01531906506256824,
 0.01342302033214055,
 0.008519160275505356,
 0.00935051078120051,
 -0.008213598537388744,
 0.010310097683174386,
 -0.00186940901016665,
 -0.01353024145611766,
 0.034160444298006236,
 0.020170535218233632,
 -0.013385587477319763,
 0.008058061329762441,
 -0.026598472338264432,
 0.006891159471461756,
 0.011647227168443077,
 0.01098493834657879,
 -0.0033641747456320988,
 -0.01308919211001405,
 0.014604410227566022,
 -0.021566705558775462,
 0.03208594748870596,
 -0.00042084498401824533,
 0.007451599308421019,
 -0.002610009720613287,
 0.022243087384808333,
 -0.004008021397538822,
 0.008810629682154906,
 0.001285695129061505,
 0.025114500121415008,
 0.007524027817480797,
 0.023660326036590004,
 0.011112894062119509,
 0.009634894930946249,
 -0.01428416719070485,
 0.003871933355528405,
 0.02227806080940098,
 0.011954979664687178,
 -0.0009647854100988899,
 0.022663859577212085,
 0.006627160634382369,
 -0.0019579056670573137,
 0.01176803659536177,
 0.010902097514203476,
 0.008643096156020014,
 0.015658682933195955,
 0.0034010873740284073,
 0.0,
 -0.004822606659931196,
 0.02919915469226235,
 0.039124794492232225,
 0.003785493479481886,
 0.05011509425456015,
 -0.008154434965164298,
 0.004246965415927549,
 -0.0011124355537358006,
 0.006099379460150816,
 -0.001280058691747491,
 0.0013226543187687075,
 0.0006856586101923347,
 0.00521383528814545,
 -0.016948209287764797,
 0.007816446842320862,
 0.016968373573723855,
 0.005558786751636117,
 -0.0025191814536627715,
 0.0037708529091436335,
 0.0024389630755235446,
 0.016748410203382136,
 0.0011269713174185958,
 -0.010677017935881078,
 -0.018634918416293566,
 0.0,
 0.0328827415388681,
 0.0192819295494505,
 0.017625482953154515,
 -0.009286685568204334,
 0.000833333381558853,
 0.023164197039798027,
 0.0014630580517603152,
 0.007701678624017861,
 -0.003412002172805287,
 0.0010125301459913529,
 -0.009919162507737224,
 0.0034947614200984845,
 0.012412677527309443,
 0.048590184166765596,
 0.010326098539220594,
 0.0017088179141117653,
 0.005530987551533779,
 0.0,
 -0.010272303989080373,
 0.01417777896956912,
 0.012334495703795228,
 0.0025195730057210267,
 0.013865434087745395,
 0.025218727778782462,
 0.01238270611038184,
 0.0012505199102336114,
 0.056282597626633374,
 0.013312399451060277,
 -0.0050948312867086605,
 8.695274124000007e-05,
 0.008235458818434686,
 0.0011303267847517983,
 0.013618004368440496,
 0.040668254801296065,
 -0.0005600672227047624,
 0.015539019020743975,
 0.027613639931892194,
 -0.001414627481629943,
 -0.004326896275418076,
 0.011866866779899262,
 -0.013908647406320793,
 -0.01117987519847173,
 0.0002267163522850367,
 -0.008032171697264267,
 0.0016012813669738276,
 0.00807527750829067,
 0.015186320707985519,
 -0.000911992767269462,
 0.030913870253314456,
 0.007990641811786376,
 0.04624638038896615,
 0.00988617551167922,
 -0.018600634169549168,
 0.01143213413431206,
 0.0,
 0.019352579119365415,
 -0.003084382264591573,
 0.00041296717497893816,
 0.02638675517319503,
 0.022851264916768057,
 0.011275909782542408,
 0.002786914461961327,
 0.0014781968693109652,
 0.007159606516085281,
 0.01320534574977416,
 0.004139568300421224,
 0.007732716563054053,
 0.01327227241663021,
 0.004337774297382793,
 -0.00751883241402734,
 0.015296973266584192,
 0.006564822671365843,
 -0.007922402300384625,
 0.019896585339436102,
 0.008654119144462557,
 0.006217636610870582,
 0.01154326304606594,
 0.0038624566526414884,
 0.0016500141244679735,
 -0.008267137704893663,
 -0.010610179112015459,
 0.009764113374905141,
 0.024692612590371414,
 0.0028943580263645565,
 -0.011054428324385853,
 -0.004893403682729236,
 0.006888233509661492,
 0.0013227515156165315,
 0.0026812277141598857,
 0.014528100562909808,
 0.008545014959236295,
 -0.003855691915197602,
 -0.01245234003464162,
 0.0026493423684192663,
 -0.0005799555007535643,
 -0.004491025512463827,
 -0.026061000342084917,
 0.028428951818734432,
 0.00891006785655194,
 0.002377886783779706,
 -0.012060932565873794,
 0.0006271558687846854,
 -0.015498890769847676,
 -0.010087552820079074,
 0.0045059619207061365,
 0.01212136053234482,
 0.0,
 0.019554210949106702,
 0.0048318250481574326,
 0.03919224380764727,
 -0.011465478109278096,
 0.005896060525127444,
 -0.005069076878946281,
 0.0060086972816174354,
 0.013412109197873494,
 0.004834820054583311,
 0.02272825107755609,
 0.029496173921585555,
 0.005360027126084106,
 0.025571996703995816,
 0.008766493212182373,
 0.01562803121336009,
 -0.004664753250516642,
 0.013674196514230904,
 -0.0013264360613070073,
 0.002298851587110649,
 -0.005167351992231486,
 -0.0013390724143441293,
 0.007185509655160865,
 -0.011666536233829308,
 0.01559290587240282,
 -0.006459076665705312,
 -0.011935254870547796,
 0.0015860431556347797,
 0.01691585464049713,
 0.0,
 0.02810910957143406,
 0.008506302096144268,
 0.008630594527701173,
 -0.0005021340803472585,
 0.0318669629778937,
 -0.008464442616150017,
 0.00026684456462536016,
 0.017245038423439794,
 0.007176803323456777,
 0.006273546297238237,
 0.0038200386012387185,
 0.013868897925445246,
 -0.0080201866067167,
 0.0032000027306708497,
 0.004510977507963371,
 0.004082828652007207,
 0.0018696359657079922,
 0.004405103214937982,
 0.001649794149981625,
 -0.008523124772208252,
 0.03198304585305074,
 0.014696648826253643,
 -0.0022547923870890937,
 0.006264445148414695,
 0.0,
 0.0012570711900511137,
 0.00599975713952617,
 0.003626178359453665,
 0.008455994914992907,
 0.011313759900273534,
 0.014935558085877003,
 -0.003565066164496257,
 -0.00025003125520928253,
 0.011028331041478233,
 0.01153625423054365,
 0.013263048817049893,
 0.047643594198609855,
 -0.006649354306636968,
 0.0,
 -0.009063506153346853,
 0.0025475029369018023,
 0.0054073057130661056,
 0.009299989529589579,
 0.010664397893060791,
 -0.0022837577724900103,
 0.007769315125612974,
 0.030568757174731735,
 0.0072580963789818705,
 -0.002881602129583067,
 0.002979061171057472,
 0.02558502203648041,
 0.003851920020527974,
 0.017117234649854075,
 -0.0030758739219922233,
 0.010614812464993085,
 0.02985296314968113,
 0.018882187721330015,
 0.0006430868388832155,
 0.008984786407815257,
 -0.00012904058344257848,
 0.007567070159330264,
 -0.014807388355697167,
 0.001253246616357167,
 0.021856016108021722,
 0.005806093337865756,
 -0.01638609033712662,
 0.005966604813221696,
 0.013094117221041495,
 -0.0008737440485968834,
 -0.006032665563092656,
 0.002426989299060935,
 0.0031931905791549855,
 -0.00220353604976841,
 0.0030468105124025397,
 -0.003459266080471454,
 0.014588410296488392,
 -0.011423674319029345,
 0.0016262475114845584,
 0.001944895264605745,
 -0.013127855092532996,
 -0.007111843487717475,
 0.003080310466379769,
 0.03309505760177626,
 0.02387552365824669,
 0.004586056794719649,
 0.013346241952894704,
 0.0062521273871161505,
 0.013245226750020505,
 -0.005563891948049346,
 0.027616528967847012,
 0.04402988215923385,
 0.04930427656572336,
 0.007035859643616912,
 0.0017381232649292583,
 -0.004477619421294611,
 0.009333560637666561,
 -0.007662872745569137,
 0.017418810509416335,
 0.004912407386340368,
 0.01690795664970067,
 0.013245226750020505,
 -0.0027024234303466925,
 -0.003139720004667641,
 -0.0030196298737199456,
 0.0007171029349968235,
 0.011605704466903512,
 0.0034838572018483687,
 0.011629916253898266,
 0.018356791582426295,
 -0.0021905813798184753,
 0.030305349495328843,
 0.010653631894421155,
 -0.0010782004974602606,
 -0.004322880697764836,
 -0.011274076573218108,
 0.005669644929995995,
 -0.005152437332588584,
 0.02031115812712298,
 0.010425172686228145,
 0.0035211303985789606,
 0.008287340248570287,
 -0.013979724408268902,
 0.008378121361235093,
 0.003292726056975907,
 0.0394632842476812,
 0.012378584232639971,
 0.020604113732031592,
 0.008948605576014014,
 -0.03155683134175922,
 -0.004008021397538711,
 0.005925666430307624,
 0.0015140048312150113,
 0.0037027752463733208,
 -0.0009111617942457701,
 0.01153215391914782,
 0.00921156108199579,
 -0.003673276242406077,
 0.010652180757722745,
 -0.0013424889515976455,
 0.028774023487820852,
 -0.007252568563912375,
 0.003252849108664581,
 0.0064803785397345255,
 -0.0066792755939173755,
 0.01615544022228499]

In [101]:
pd.DataFrame(
    [
        [x for x in range(10)],
        [x for x in range(10, 20)],
    ],
    columns=[x for x in range(10)])

    0   1   2   3   4   5   6   7   8   9
0   0   1   2   3   4   5   6   7   8   9
1  10  11  12  13  14  15  16  17  18  19

In [103]:
list(ret.columns)

['AMAZON.COM',
 'ABBOTT LABORATORIES',
 'AES',
 'ABIOMED',
 'INTERNATIONAL BUS.MCHS.',
 'ADVANCED MICRO DEVC.',
 'ADOBE SYSTEMS',
 'ALEXANDRIA RLST.EQTIES.',
 'AIR PRDS.& CHEMS.',
 'ALASKA AIR GROUP',
 'BOSTON PROPERTIES',
 'ALLSTATE',
 'HONEYWELL INTL.',
 'AMGEN',
 'HESS',
 'AMERICAN EXPRESS',
 'AMER.ELEC.PWR.',
 'AFLAC',
 'AMERICAN INTL.GP.',
 'ANALOG DEVICES',
 'ANADARKO PETROLEUM',
 'ALEXION PHARMS.',
 'VALERO ENERGY',
 'APACHE',
 "COMCAST 'A'",
 'ANSYS',
 'APPLE',
 'APPLIED MATS.',
 'ALBEMARLE',
 'ARCHER-DANLS.-MIDL.',
 'PINNACLE WEST CAP.',
 'AMEREN',
 "APARTMENT INV.& MAN.'A'",
 'AUTODESK',
 'AUTOMATIC DATA PROC.',
 'AUTOZONE',
 'AVERY DENNISON',
 'BALL',
 "BERKSHIRE HATHAWAY 'B'",
 'BAXTER INTL.',
 'BECTON DICKINSON',
 'AMETEK',
 'VERIZON COMMUNICATIONS',
 'BEST BUY',
 'SL GREEN REALTY',
 'YUM! BRANDS',
 'FIRSTENERGY',
 'H&R BLOCK',
 'BOEING',
 'ROBERT HALF INTL.',
 'BORGWARNER',
 'BOSTON SCIENTIFIC',
 'CH ROBINSON WWD.',
 'TAKE TWO INTACT.SFTW.',
 'METTLER TOLEDO INTL.',
 'BRISTOL MYERS SQUIBB',
 'AFFILIATED MANAGERS',
 'ONEOK',
 'AVALONBAY COMMNS.',
 'UNITED RENTALS',
 'SEMPRA EN.',
 'FEDEX',
 'VERISIGN',
 "AMPHENOL 'A'",
 "BROWN-FORMAN 'B'",
 'QUANTA SERVICES',
 'CSX',
 "CABOT OIL & GAS 'A'",
 'CAMPBELL SOUP',
 "CONSTELLATION BRANDS 'A'",
 'CARDINAL HEALTH',
 'CATERPILLAR',
 'CELGENE',
 'CITRIX SYS.',
 'CENTURYLINK',
 'CERNER',
 'JP MORGAN CHASE & CO.',
 'CHURCH & DWIGHT CO.',
 'CIGNA',
 'CINCINNATI FINL.',
 'CINTAS',
 'CISCO SYSTEMS',
 'CLOROX',
 'COCA COLA',
 'COLGATE-PALM.',
 "MARRIOTT INTL.'A'",
 'COMERICA',
 'CA',
 'CONAGRA BRANDS',
 'CONSOLIDATED EDISON',
 'CMS ENERGY',
 'COOPER COS.',
 'CORNING',
 'SEALED AIR',
 'CUMMINS',
 'D R HORTON',
 'DANAHER',
 "MOODY'S",
 "COGNIZANT TECH.SLTN.'A'",
 'TARGET',
 'DEERE',
 'MORGAN STANLEY',
 "REPUBLIC SVS.'A'",
 'WALT DISNEY',
 'DOLLAR TREE',
 'DOVER',
 'OMNICOM GROUP',
 'DTE ENERGY',
 'DUKE REALTY',
 'FLOWSERVE',
 'DARDEN RESTAURANTS',
 'EBAY',
 'BANK OF AMERICA',
 'CITIGROUP',
 'EASTMAN CHEMICAL',
 'E*TRADE FINANCIAL',
 'CADENCE DESIGN SYS.',
 "DISH NETWORK 'A'",
 'ECOLAB',
 'PERKINELMER',
 'ELECTRONIC ARTS',
 'EMERSON ELECTRIC',
 'ESSEX PROPERTY TST.',
 'ENTERGY',
 'EOG RES.',
 'EQUIFAX',
 'EQUITY RESD.TST.PROPS. SHBI',
 'EQT',
 "ESTEE LAUDER COS.'A'",
 'EXPEDITOR INTL.OF WASH.',
 'EXXON MOBIL',
 'FMC',
 'NEXTERA ENERGY',
 'FASTENAL',
 'FEDERAL REALTY INV.TST.',
 'FIFTH THIRD BANCORP',
 'M&T BANK',
 'FISERV',
 'FLIR SYSTEMS',
 "MACY'S",
 'FRANKLIN RESOURCES',
 'FREEPORT-MCMORAN',
 'ARTHUR J GALLAGHER',
 'GAP',
 'GENERAL DYNAMICS',
 'GENERAL MILLS',
 'GENUINE PARTS',
 'GILEAD SCIENCES',
 "GARTNER 'A'",
 'GOODYEAR TIRE & RUB.',
 'MCKESSON',
 'NVIDIA',
 'GENERAL ELECTRIC',
 'WW GRAINGER',
 'HALLIBURTON',
 'GOLDMAN SACHS GP.',
 'HARLEY-DAVIDSON',
 'HARRIS',
 'HASBRO',
 'HENRY SCHEIN',
 'HCP',
 'HELMERICH & PAYNE',
 'HERSHEY',
 'F5 NETWORKS',
 'JUNIPER NETWORKS',
 'HOLOGIC',
 'UNUM GROUP',
 'HOME DEPOT',
 'HORMEL FOODS',
 'CENTERPOINT EN.',
 'HUMANA',
 'HUNT JB TRANSPORT SVS.',
 'HUNTINGTON BCSH.',
 'RED HAT',
 'NEKTAR THERAPEUTICS',
 'BIOGEN',
 'ILLINOIS TOOL WORKS',
 'INTUIT',
 'IDEXX LABORATORIES',
 'INTEL',
 'INTL.FLAVORS & FRAG.',
 'INTERNATIONAL PAPER',
 'INTERPUBLIC GROUP',
 'JACOBS ENGR.',
 'INCYTE',
 'JOHNSON & JOHNSON',
 'HARTFORD FINL.SVS.GP.',
 'KLA TENCOR',
 'DEVON ENERGY',
 'KELLOGG',
 'KEYCORP',
 'KIMCO REALTY',
 'KIMBERLY-CLARK',
 'BLACKROCK',
 "KOHL'S",
 'KROGER',
 'LAM RESEARCH',
 'AKAMAI TECHS.',
 'LEGGETT&PLATT',
 "LENNAR 'A'",
 'ELI LILLY',
 'LINCOLN NATIONAL',
 "UNITED PARCEL SER.'B'",
 'AGILENT TECHS.',
 'LOCKHEED MARTIN',
 'LOEWS',
 'CARNIVAL',
 "LOWE'S COMPANIES",
 'DOMINION ENERGY',
 'MACERICH',
 'SCANA',
 'MGM RESORTS INTL.',
 'MCCORMICK & COMPANY NV.',
 'MCDONALDS',
 'EVEREST RE GP.',
 'HOST HOTELS & RESORTS',
 'MARSH & MCLENNAN',
 'MASCO',
 'MARTIN MRTA.MATS.',
 'MATTEL',
 'ACTIVISION BLIZZARD',
 'CVS HEALTH',
 'LABORATORY CORP.OF AM. HDG.',
 'MICROSOFT',
 'MICRON TECHNOLOGY',
 'MID-AMER.APT COMMUNITIES',
 'MICROCHIP TECH.',
 '3M',
 'MOHAWK INDUSTRIES',
 'KANSAS CITY SOUTHERN',
 'XCEL ENERGY',
 'FORD MOTOR',
 'NATIONAL OILWELL VARCO',
 'NETAPP',
 'NEWFIELD EXPLORATION',
 'NEWELL BRANDS',
 'NEWMONT MINING',
 "NIKE 'B'",
 'NOBLE ENERGY',
 'NORDSTROM',
 'NORFOLK SOUTHERN',
 'NISOURCE',
 'NORTHERN TRUST',
 'NORTHROP GRUMMAN',
 'WELLS FARGO & CO',
 'NUCOR',
 'CAPITAL ONE FINL.',
 'OCCIDENTAL PTL.',
 'ORACLE',
 'PACCAR',
 'EXELON',
 'PARKER-HANNIFIN',
 'PAYCHEX',
 'PPL',
 'PEPSICO',
 'PFIZER',
 'CONOCOPHILLIPS',
 'PG&E',
 'PIONEER NTRL.RES.',
 'ALTRIA GROUP',
 'PNC FINL.SVS.GP.',
 'AETNA',
 'PPG INDUSTRIES',
 'PRAXAIR',
 'COSTCO WHOLESALE',
 'T ROWE PRICE GROUP',
 'QUEST DIAGNOSTICS',
 'PROCTER & GAMBLE',
 'PROGRESSIVE OHIO',
 'PUB.SER.ENTER.GP.',
 'PULTEGROUP',
 'QUALCOMM',
 'RAYMOND JAMES FINL.',
 'REALTY INCOME',
 'REGENCY CENTERS',
 'UDR',
 'REGENERON PHARMS.',
 'RESMED',
 'US BANCORP',
 'ROSS STORES',
 'ROPER TECHNOLOGIES',
 'ROCKWELL AUTOMATION',
 'ROYAL CARIBBEAN CRUISES',
 "RAYTHEON 'B'",
 'TRAVELERS COS.',
 'MERCK & COMPANY',
 'SCHLUMBERGER',
 'CHARLES SCHWAB',
 'AMERISOURCEBERGEN',
 'SHERWIN-WILLIAMS',
 'SVB FINANCIAL GROUP',
 'SIMON PROPERTY GROUP',
 'SMITH (AO)',
 'SNAP-ON',
 'EDISON INTL.',
 'SOUTHERN',
 'BB&T',
 'SOUTHWEST AIRLINES',
 'AT&T',
 'CHEVRON',
 'STATE STREET',
 'STARBUCKS',
 'PUBLIC STORAGE',
 'STRYKER',
 'STERICYCLE',
 'SUNTRUST BANKS',
 'SYMANTEC',
 'SYNOPSYS',
 'SYSCO',
 'TEXAS INSTRUMENTS',
 'TEXTRON',
 'THERMO FISHER SCIENTIFIC',
 'TIFFANY & CO',
 'TORCHMARK',
 'TOTAL SYSTEM SERVICES',
 'DAVITA',
 'TRACTOR SUPPLY',
 "TYSON FOODS 'A'",
 'MARATHON OIL',
 'UNION PACIFIC',
 'UNITED TECHNOLOGIES',
 'UNITEDHEALTH GROUP',
 "UNIVERSAL HEALTH SVS.'B'",
 'VARIAN MEDICAL SYSTEMS',
 'VENTAS',
 'V F',
 'VERTEX PHARMS.',
 'VULCAN MATERIALS',
 'VORNADO REALTY TRUST',
 'WALMART',
 'WASTE MANAGEMENT',
 'WATERS',
 'J M SMUCKER',
 'WESTERN DIGITAL',
 'WEYERHAEUSER',
 'WHIRLPOOL',
 'SKYWORKS SOLUTIONS',
 'WILLIAMS',
 'ALLIANT ENERGY CORP.',
 'FOOT LOCKER',
 'CARMAX',
 'XILINX',
 'TJX',
 'ZIONS BANCORP.',
 'REGIONS FINL.NEW',
 "MOLSON COORS BREWING 'B'",
 "VIACOM 'B'",
 "CBS 'B'",
 'PEOPLES UNITED FINANCIAL',
 'BANK OF NEW YORK MELLON',
 'CHUBB',
 'MOSAIC',
 'STANLEY BLACK & DECKER',
 'PVH',
 'PROLOGIS',
 'RALPH LAUREN CL.A',
 'MOTOROLA SOLUTIONS',
 'AON CLASS A',
 'HOLLYFRONTIER',
 'INGERSOLL-RAND',
 'O REILLY AUTOMOTIVE',
 'AMERICAN TOWER',
 'EXPRESS SCRIPTS HOLDING',
 'DUKE ENERGY',
 'EATON',
 'L BRANDS',
 'ARCONIC',
 'ENVISION HEALTHCARE',
 'XL GROUP',
 'BAKER HUGHES A',
 'BOOKING HOLDINGS',
 'ANDEAVOR',
 'EVERGY',
 'JEFFERIES FINANCIAL GROUP',
 'PERRIGO',
 'PENTAIR',
 'QORVO',
 'CROWN CASTLE INTL.',
 'MEDTRONIC',
 'WALGREENS BOOTS ALLIANCE',
 'MYLAN',
 'IRON MOUNTAIN',
 'EVERSOURCE ENERGY',
 'JOHNSON CONTROLS INTL.',
 'ALLERGAN',
 'GGP',
 'DENTSPLY SIRONA',
 'S&P GLOBAL',
 'WELLTOWER',
 'XEROX',
 'HP',
 'DXC TECHNOLOGY',
 'WEC ENERGY GROUP',
 'L3 TECHNOLOGIES',
 'MONSTER BEVERAGE',
 'SBA COMMS.']

In [104]:
ret.head()

,AMAZON.COM,ABBOTT LABORATORIES,AES,ABIOMED,INTERNATIONAL BUS.MCHS.,ADVANCED MICRO DEVC.,ADOBE SYSTEMS,ALEXANDRIA RLST.EQTIES.,AIR PRDS.& CHEMS.,ALASKA AIR GROUP,...,DENTSPLY SIRONA,S&P GLOBAL,WELLTOWER,XEROX,HP,DXC TECHNOLOGY,WEC ENERGY GROUP,L3 TECHNOLOGIES,MONSTER BEVERAGE,SBA COMMS.
0,0.009078,0.003038,0.023104,0.011834,-0.001705,0.057158,0.041341,0.022843,0.007071,-0.013245,...,0.006313,0.003673,0.018993,0.017592,0.004881,0.010801,0.021277,0.013493,0.050852,0.028636
1,-0.006960,0.001515,0.041710,0.028468,-0.001341,0.004926,-0.002599,0.003878,-0.011472,0.019664,...,0.009212,-0.003673,0.010652,-0.001342,0.028774,-0.007253,0.003253,0.006480,-0.006679,0.016155
2,0.008430,0.012797,-0.009518,-0.007303,0.006689,0.033820,-0.009152,0.012739,-0.008692,-0.010908,...,-0.011435,-0.000969,0.020409,-0.010803,-0.007114,0.075583,-0.004005,-0.006879,-0.011340,0.000000
3,0.004606,0.019009,0.016010,0.020726,0.029265,0.002965,0.024135,0.011399,0.023012,-0.008472,...,0.015461,0.016726,0.004200,-0.006131,0.028166,0.006547,0.007496,0.011746,0.050511,0.000534
4,-0.016641,0.036495,-0.017206,0.040206,-0.014466,-0.015814,-0.016023,0.012903,-0.012794,0.016036,...,0.009815,-0.017308,0.014149,0.013571,0.012493,-0.008557,0.004471,0.009401,0.050881,0.006386

In [106]:
ret.shape

(3234, 396)

In [107]:
ret.index

RangeIndex(start=0, stop=3234, step=1)

In [111]:
(len(ret.index)-60) // 20

158

In [113]:
[1]

[1]

In [114]:
def fn():
    return [], 1, 2

a, b, c = fn()
a

[]

In [115]:
b

1

In [116]:
c

2

In [134]:

df = pd.read_excel('../Naive_S_P500.xlsx', sheet_name='price')
price = copy.deepcopy(df.drop(columns=['Unnamed: 0'])).iloc[:, 1:397]
comp_name = list(price.columns)
w_plus_df, w_minus_df = pd.DataFrame(columns=list(comp_name), ), pd.DataFrame(columns=list(comp_name), )

In [133]:
price
comp_

,Date,AMAZON.COM,ABBOTT LABORATORIES,AES,ABIOMED,INTERNATIONAL BUS.MCHS.,ADVANCED MICRO DEVC.,ADOBE SYSTEMS,ALEXANDRIA RLST.EQTIES.,AIR PRDS.& CHEMS.,...,DENTSPLY SIRONA,S&P GLOBAL,WELLTOWER,XEROX,HP,DXC TECHNOLOGY,WEC ENERGY GROUP,L3 TECHNOLOGIES,MONSTER BEVERAGE,SBA COMMS.
0,2006-03-27,35.25,20.7944,16.93,13.1300,83.08,35.33,35.79,94.61,61.2574,...,28.710,56.99,37.13,39.6243,15.0321,20.7603,20.00,82.0495,5.0470,24.19
1,2006-04-24,35.79,19.6844,16.70,13.4900,82.11,32.81,37.20,90.50,63.9107,...,29.505,57.45,35.06,36.8843,14.9368,21.3689,19.64,81.8002,5.8354,23.73
2,2006-05-22,34.83,19.9763,18.03,12.1200,80.02,33.18,29.91,84.95,58.7889,...,29.875,51.74,33.52,36.0939,14.6099,20.1700,19.71,77.3309,7.4308,20.60
3,2006-06-19,35.07,20.2490,16.91,12.3600,77.67,24.95,28.78,84.48,56.9307,...,29.515,51.70,34.28,35.9886,15.2410,20.2173,19.64,71.6531,6.6146,22.23
4,2006-07-17,33.67,21.2825,19.75,12.4200,73.70,20.92,27.59,89.65,56.8660,...,29.230,48.82,34.73,35.9095,14.1650,18.4682,20.27,71.0585,7.8583,22.66
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,2018-01-15,1305.20,58.8400,11.04,215.1100,163.14,12.02,195.05,125.12,170.1500,...,65.790,177.64,59.16,32.7700,22.9200,87.6098,63.63,209.4600,63.7700,155.94
155,2018-02-12,1386.23,57.4100,10.27,233.7200,151.40,11.68,192.15,119.08,159.6800,...,57.380,180.36,54.27,29.9500,20.4100,84.6776,61.28,204.4400,64.0800,159.63
156,2018-03-12,1598.39,63.6200,10.74,294.7400,160.26,11.52,220.94,126.03,170.8800,...,58.420,195.96,54.73,29.6900,23.8300,91.7528,60.89,204.7700,58.4300,168.91
157,2018-04-09,1406.08,58.2200,11.39,288.1201,152.69,9.53,219.17,121.34,160.2300,...,49.250,187.77,54.49,27.5300,20.8900,86.5286,62.64,208.6700,56.2300,171.58
158,2018-05-07,1600.14,59.3200,12.37,347.5701,143.22,11.59,230.99,129.80,163.4500,...,46.920,193.38,55.71,28.4600,21.7900,87.6703,64.03,188.4000,53.3100,157.60

In [135]:
w_df = pd.DataFrame(columns=list(comp_name), )

In [136]:
w_df

Empty DataFrame
Columns: [AMAZON.COM, ABBOTT LABORATORIES, AES, ABIOMED, INTERNATIONAL BUS.MCHS., ADVANCED MICRO DEVC., ADOBE SYSTEMS, ALEXANDRIA RLST.EQTIES., AIR PRDS.& CHEMS., ALASKA AIR GROUP, BOSTON PROPERTIES, ALLSTATE, HONEYWELL INTL., AMGEN, HESS, AMERICAN EXPRESS, AMER.ELEC.PWR., AFLAC, AMERICAN INTL.GP., ANALOG DEVICES, ANADARKO PETROLEUM, ALEXION PHARMS., VALERO ENERGY, APACHE, COMCAST 'A', ANSYS, APPLE, APPLIED MATS., ALBEMARLE, ARCHER-DANLS.-MIDL., PINNACLE WEST CAP., AMEREN, APARTMENT INV.& MAN.'A', AUTODESK, AUTOMATIC DATA PROC., AUTOZONE, AVERY DENNISON, BALL, BERKSHIRE HATHAWAY 'B', BAXTER INTL., BECTON DICKINSON, AMETEK, VERIZON COMMUNICATIONS, BEST BUY, SL GREEN REALTY, YUM! BRANDS, FIRSTENERGY, H&R BLOCK, BOEING, ROBERT HALF INTL., BORGWARNER, BOSTON SCIENTIFIC, CH ROBINSON WWD., TAKE TWO INTACT.SFTW., METTLER TOLEDO INTL., BRISTOL MYERS SQUIBB, AFFILIATED MANAGERS, ONEOK, AVALONBAY COMMNS., UNITED RENTALS, SEMPRA EN., FEDEX, VERISIGN, AMPHENOL 'A', BROWN-FORMAN 'B', QUANTA SERVICES, CSX, CABOT OIL & GAS 'A', CAMPBELL SOUP, CONSTELLATION BRANDS 'A', CARDINAL HEALTH, CATERPILLAR, CELGENE, CITRIX SYS., CENTURYLINK, CERNER, JP MORGAN CHASE & CO., CHURCH & DWIGHT CO., CIGNA, CINCINNATI FINL., CINTAS, CISCO SYSTEMS, CLOROX, COCA COLA, COLGATE-PALM., MARRIOTT INTL.'A', COMERICA, CA, CONAGRA BRANDS, CONSOLIDATED EDISON, CMS ENERGY, COOPER COS., CORNING, SEALED AIR, CUMMINS, D R HORTON, DANAHER, MOODY'S, COGNIZANT TECH.SLTN.'A', TARGET, ...]
Index: []

[0 rows x 396 columns]

In [141]:
# w_df.loc[len(w_df.index)]
w_df.loc[len(w_df.index)] = [x for x in range(396)]

In [142]:
w_df

,AMAZON.COM,ABBOTT LABORATORIES,AES,ABIOMED,INTERNATIONAL BUS.MCHS.,ADVANCED MICRO DEVC.,ADOBE SYSTEMS,ALEXANDRIA RLST.EQTIES.,AIR PRDS.& CHEMS.,ALASKA AIR GROUP,...,DENTSPLY SIRONA,S&P GLOBAL,WELLTOWER,XEROX,HP,DXC TECHNOLOGY,WEC ENERGY GROUP,L3 TECHNOLOGIES,MONSTER BEVERAGE,SBA COMMS.
0,0,1,2,3,4,5,6,7,8,9,...,386,387,388,389,390,391,392,393,394,395

In [145]:
print(w_df)

  AMAZON.COM ABBOTT LABORATORIES AES ABIOMED INTERNATIONAL BUS.MCHS.  \
0          0                   1   2       3                       4

  ADVANCED MICRO DEVC. ADOBE SYSTEMS ALEXANDRIA RLST.EQTIES.  \
0                    5             6                       7

  AIR PRDS.& CHEMS. ALASKA AIR GROUP  ... DENTSPLY SIRONA S&P GLOBAL  \
0                 8                9  ...             386        387

  WELLTOWER XEROX   HP DXC TECHNOLOGY WEC ENERGY GROUP L3 TECHNOLOGIES  \
0       388   389  390            391              392             393

  MONSTER BEVERAGE SBA COMMS.
0              394        395

[1 rows x 396 columns]

In [146]:
for i in range(10):
    print(i*20, i*20+60)

0 60
20 80
40 100
60 120
80 140
100 160
120 180
140 200
160 220
180 240

In [154]:
price.head()

,AMAZON.COM,ABBOTT LABORATORIES,AES,ABIOMED,INTERNATIONAL BUS.MCHS.,ADVANCED MICRO DEVC.,ADOBE SYSTEMS,ALEXANDRIA RLST.EQTIES.,AIR PRDS.& CHEMS.,ALASKA AIR GROUP,...,DENTSPLY SIRONA,S&P GLOBAL,WELLTOWER,XEROX,HP,DXC TECHNOLOGY,WEC ENERGY GROUP,L3 TECHNOLOGIES,MONSTER BEVERAGE,SBA COMMS.
0,35.25,20.7944,16.93,13.13,83.08,35.33,35.79,94.61,61.2574,8.7525,...,28.710,56.99,37.13,39.6243,15.0321,20.7603,20.00,82.0495,5.0470,24.19
1,35.79,19.6844,16.70,13.49,82.11,32.81,37.20,90.50,63.9107,9.5725,...,29.505,57.45,35.06,36.8843,14.9368,21.3689,19.64,81.8002,5.8354,23.73
2,34.83,19.9763,18.03,12.12,80.02,33.18,29.91,84.95,58.7889,9.4925,...,29.875,51.74,33.52,36.0939,14.6099,20.1700,19.71,77.3309,7.4308,20.60
3,35.07,20.2490,16.91,12.36,77.67,24.95,28.78,84.48,56.9307,9.4600,...,29.515,51.70,34.28,35.9886,15.2410,20.2173,19.64,71.6531,6.6146,22.23
4,33.67,21.2825,19.75,12.42,73.70,20.92,27.59,89.65,56.8660,8.6000,...,29.230,48.82,34.73,35.9095,14.1650,18.4682,20.27,71.0585,7.8583,22.66

In [155]:
price.iloc[0:1]

,AMAZON.COM,ABBOTT LABORATORIES,AES,ABIOMED,INTERNATIONAL BUS.MCHS.,ADVANCED MICRO DEVC.,ADOBE SYSTEMS,ALEXANDRIA RLST.EQTIES.,AIR PRDS.& CHEMS.,ALASKA AIR GROUP,...,DENTSPLY SIRONA,S&P GLOBAL,WELLTOWER,XEROX,HP,DXC TECHNOLOGY,WEC ENERGY GROUP,L3 TECHNOLOGIES,MONSTER BEVERAGE,SBA COMMS.
0,35.25,20.7944,16.93,13.13,83.08,35.33,35.79,94.61,61.2574,8.7525,...,28.71,56.99,37.13,39.6243,15.0321,20.7603,20.0,82.0495,5.047,24.19

In [161]:
price.iloc[1:2]

,AMAZON.COM,ABBOTT LABORATORIES,AES,ABIOMED,INTERNATIONAL BUS.MCHS.,ADVANCED MICRO DEVC.,ADOBE SYSTEMS,ALEXANDRIA RLST.EQTIES.,AIR PRDS.& CHEMS.,ALASKA AIR GROUP,...,DENTSPLY SIRONA,S&P GLOBAL,WELLTOWER,XEROX,HP,DXC TECHNOLOGY,WEC ENERGY GROUP,L3 TECHNOLOGIES,MONSTER BEVERAGE,SBA COMMS.
1,35.79,19.6844,16.7,13.49,82.11,32.81,37.2,90.5,63.9107,9.5725,...,29.505,57.45,35.06,36.8843,14.9368,21.3689,19.64,81.8002,5.8354,23.73

In [164]:
type(price.iloc[0])

pandas.core.series.Series

In [159]:
price.tail()

,AMAZON.COM,ABBOTT LABORATORIES,AES,ABIOMED,INTERNATIONAL BUS.MCHS.,ADVANCED MICRO DEVC.,ADOBE SYSTEMS,ALEXANDRIA RLST.EQTIES.,AIR PRDS.& CHEMS.,ALASKA AIR GROUP,...,DENTSPLY SIRONA,S&P GLOBAL,WELLTOWER,XEROX,HP,DXC TECHNOLOGY,WEC ENERGY GROUP,L3 TECHNOLOGIES,MONSTER BEVERAGE,SBA COMMS.
154,1305.20,58.84,11.04,215.1100,163.14,12.02,195.05,125.12,170.15,73.52,...,65.79,177.64,59.16,32.77,22.92,87.6098,63.63,209.46,63.77,155.94
155,1386.23,57.41,10.27,233.7200,151.40,11.68,192.15,119.08,159.68,66.01,...,57.38,180.36,54.27,29.95,20.41,84.6776,61.28,204.44,64.08,159.63
156,1598.39,63.62,10.74,294.7400,160.26,11.52,220.94,126.03,170.88,65.78,...,58.42,195.96,54.73,29.69,23.83,91.7528,60.89,204.77,58.43,168.91
157,1406.08,58.22,11.39,288.1201,152.69,9.53,219.17,121.34,160.23,59.81,...,49.25,187.77,54.49,27.53,20.89,86.5286,62.64,208.67,56.23,171.58
158,1600.14,59.32,12.37,347.5701,143.22,11.59,230.99,129.80,163.45,61.65,...,46.92,193.38,55.71,28.46,21.79,87.6703,64.03,188.40,53.31,157.60

In [180]:
df = pd.DataFrame([price.iloc[0]], index=[0])

In [181]:
df.head()
df.shape

(1, 396)

In [182]:
df.head()

,AMAZON.COM,ABBOTT LABORATORIES,AES,ABIOMED,INTERNATIONAL BUS.MCHS.,ADVANCED MICRO DEVC.,ADOBE SYSTEMS,ALEXANDRIA RLST.EQTIES.,AIR PRDS.& CHEMS.,ALASKA AIR GROUP,...,DENTSPLY SIRONA,S&P GLOBAL,WELLTOWER,XEROX,HP,DXC TECHNOLOGY,WEC ENERGY GROUP,L3 TECHNOLOGIES,MONSTER BEVERAGE,SBA COMMS.
0,35.25,20.7944,16.93,13.13,83.08,35.33,35.79,94.61,61.2574,8.7525,...,28.71,56.99,37.13,39.6243,15.0321,20.7603,20.0,82.0495,5.047,24.19

In [189]:
df.iloc[0, :].shape

(396,)

In [193]:
list(df.iloc[0, :])

[35.25,
 20.7944,
 16.93,
 13.13,
 83.08,
 35.33,
 35.79,
 94.61,
 61.2574,
 8.7525,
 90.9,
 52.53,
 41.7609,
 73.1,
 47.3467,
 53.36,
 34.44,
 23.14,
 1125.151,
 37.77,
 50.2,
 8.7,
 54.2785,
 65.95,
 8.9067,
 25.83,
 8.5014,
 17.85,
 21.425,
 35.03,
 39.91,
 50.2,
 31.7379,
 37.0,
 36.8232,
 98.85,
 60.06,
 11.0,
 59.9,
 21.1926,
 62.94,
 12.7378,
 31.3024,
 54.75,
 98.64,
 17.6527,
 49.75,
 21.74,
 78.39,
 38.95,
 15.0825,
 23.43,
 49.37,
 18.0,
 60.27,
 25.11,
 103.3,
 13.6615,
 105.94,
 32.2,
 46.67,
 112.74,
 23.5,
 12.59,
 16.8789,
 15.62,
 9.9367,
 6.0075,
 32.17,
 25.65,
 53.7241,
 75.38,
 20.715,
 28.2303,
 39.45,
 11.6675,
 42.11,
 9.3075,
 44.2033,
 43.65,
 42.63,
 21.69,
 61.95,
 21.195,
 28.885,
 32.1025,
 58.01,
 27.13,
 16.4034,
 44.18,
 13.05,
 54.94,
 27.67,
 29.28,
 26.5075,
 33.71,
 24.3026,
 70.47,
 14.415,
 53.17,
 39.26,
 51.5667,
 27.8266,
 26.9765,
 9.2567,
 32.8015,
 42.285,
 41.0,
 36.82,
 19.3733,
 36.8024,
 15.6356,
 46.82,
 476.4001,
 25.385,
 257.3997,
 17.96,
 26.4107,
 38.9,
 23.19,
 52.29,
 42.285,
 107.02,
 69.42,
 35.955,
 37.72,
 46.05,
 36.28,
 18.77,
 41.445,
 61.29,
 15.4475,
 40.47,
 22.62,
 71.58,
 41.33,
 115.76,
 10.5125,
 14.24,
 35.825,
 32.48,
 28.095,
 28.44,
 18.35,
 64.84,
 25.285,
 44.2,
 15.61,
 13.7,
 14.01,
 51.85,
 17.7833,
 33.79,
 74.8,
 35.795,
 155.0,
 52.21,
 42.9873,
 20.8,
 23.505,
 25.4811,
 33.275,
 53.01,
 34.44,
 19.34,
 27.635,
 20.53,
 42.99,
 8.255,
 11.92,
 53.99,
 22.1,
 24.31,
 28.8,
 19.69,
 43.4575,
 48.385,
 25.935,
 21.3425,
 19.75,
 34.62,
 34.407,
 10.05,
 42.85,
 5.97,
 59.94,
 80.15,
 49.06,
 60.61,
 44.63,
 37.33,
 38.12,
 56.8945,
 139.6,
 51.81,
 10.285,
 43.17,
 29.22,
 24.98,
 59.2915,
 58.67,
 55.28,
 78.89,
 24.7139,
 75.93,
 33.56,
 48.13,
 32.95,
 35.3,
 66.5385,
 39.73,
 42.05,
 34.24,
 34.55,
 91.51,
 20.3728,
 30.15,
 28.3976,
 102.13,
 18.0,
 7.015,
 29.77,
 59.31,
 27.01,
 14.77,
 56.05,
 35.45,
 76.84,
 85.81,
 24.18,
 18.39,
 8.06,
 27.834,
 35.05,
 40.61,
 26.13,
 50.52,
 10.6812,
 21.58,
 40.25,
 53.7,
 8.0675,
 53.06,
 62.1598,
 32.465,
 52.16,
 82.48,
 45.1178,
 13.84,
 31.6311,
 53.97,
 53.6,
 40.27,
 28.1444,
 58.99,
 25.81,
 48.1024,
 40.34,
 42.63,
 16.6767,
 69.72,
 49.98,
 31.24,
 55.37,
 54.77,
 37.495,
 52.33,
 58.29,
 26.0325,
 32.695,
 40.4,
 49.71,
 29.44,
 24.12,
 65.8,
 27.89,
 16.89,
 21.655,
 30.91,
 7.2125,
 45.88,
 72.3,
 42.12,
 45.59,
 41.24,
 36.02,
 61.475,
 17.42,
 22.7867,
 50.69,
 53.04,
 78.4254,
 8.795,
 38.65,
 42.91,
 33.01,
 39.88,
 17.47,
 27.31,
 58.21,
 60.66,
 18.295,
 79.1,
 44.78,
 32.83,
 74.86,
 16.03,
 21.39,
 32.22,
 31.27,
 46.3,
 36.0,
 38.51,
 25.1467,
 20.01,
 29.725,
 16.6725,
 13.75,
 23.7209,
 23.27,
 59.22,
 54.93,
 24.975,
 49.7142,
 28.6988,
 13.955,
 35.56,
 86.27,
 69.133,
 47.95,
 34.24,
 42.83,
 39.63,
 19.0,
 30.2282,
 90.0,
 6.75,
 16.9603,
 16.145,
 24.02,
 17.64,
 25.44,
 12.605,
 83.51,
 35.78,
 34.55,
 38.72,
 24.78,
 15.6811,
 36.8454,
 53.6,
 14.36,
 50.98,
 38.99,
 53.96,
 60.41,
 90.7973,
 41.7,
 18.135,
 34.7772,
 35.79,
 30.23,
 22.185,
 50.8264,
 35.63,
 24.52,
 68.348,
 23.11,
 64.49,
 46.6305,
 23.67,
 32.77,
 20.89,
 28.8213,
 16.02,
 27.1765,
 33.2,
 29.27,
 51.84,
 45.02,
 23.87,
 23.0568,
 20.01,
 19.685,
 28.62,
 36.8551,
 28.71,
 56.99,
 37.13,
 39.6243,
 15.0321,
 20.7603,
 20.0,
 82.0495,
 5.047,
 24.19]

In [196]:
list(df.iloc[-1])

[35.25,
 20.7944,
 16.93,
 13.13,
 83.08,
 35.33,
 35.79,
 94.61,
 61.2574,
 8.7525,
 90.9,
 52.53,
 41.7609,
 73.1,
 47.3467,
 53.36,
 34.44,
 23.14,
 1125.151,
 37.77,
 50.2,
 8.7,
 54.2785,
 65.95,
 8.9067,
 25.83,
 8.5014,
 17.85,
 21.425,
 35.03,
 39.91,
 50.2,
 31.7379,
 37.0,
 36.8232,
 98.85,
 60.06,
 11.0,
 59.9,
 21.1926,
 62.94,
 12.7378,
 31.3024,
 54.75,
 98.64,
 17.6527,
 49.75,
 21.74,
 78.39,
 38.95,
 15.0825,
 23.43,
 49.37,
 18.0,
 60.27,
 25.11,
 103.3,
 13.6615,
 105.94,
 32.2,
 46.67,
 112.74,
 23.5,
 12.59,
 16.8789,
 15.62,
 9.9367,
 6.0075,
 32.17,
 25.65,
 53.7241,
 75.38,
 20.715,
 28.2303,
 39.45,
 11.6675,
 42.11,
 9.3075,
 44.2033,
 43.65,
 42.63,
 21.69,
 61.95,
 21.195,
 28.885,
 32.1025,
 58.01,
 27.13,
 16.4034,
 44.18,
 13.05,
 54.94,
 27.67,
 29.28,
 26.5075,
 33.71,
 24.3026,
 70.47,
 14.415,
 53.17,
 39.26,
 51.5667,
 27.8266,
 26.9765,
 9.2567,
 32.8015,
 42.285,
 41.0,
 36.82,
 19.3733,
 36.8024,
 15.6356,
 46.82,
 476.4001,
 25.385,
 257.3997,
 17.96,
 26.4107,
 38.9,
 23.19,
 52.29,
 42.285,
 107.02,
 69.42,
 35.955,
 37.72,
 46.05,
 36.28,
 18.77,
 41.445,
 61.29,
 15.4475,
 40.47,
 22.62,
 71.58,
 41.33,
 115.76,
 10.5125,
 14.24,
 35.825,
 32.48,
 28.095,
 28.44,
 18.35,
 64.84,
 25.285,
 44.2,
 15.61,
 13.7,
 14.01,
 51.85,
 17.7833,
 33.79,
 74.8,
 35.795,
 155.0,
 52.21,
 42.9873,
 20.8,
 23.505,
 25.4811,
 33.275,
 53.01,
 34.44,
 19.34,
 27.635,
 20.53,
 42.99,
 8.255,
 11.92,
 53.99,
 22.1,
 24.31,
 28.8,
 19.69,
 43.4575,
 48.385,
 25.935,
 21.3425,
 19.75,
 34.62,
 34.407,
 10.05,
 42.85,
 5.97,
 59.94,
 80.15,
 49.06,
 60.61,
 44.63,
 37.33,
 38.12,
 56.8945,
 139.6,
 51.81,
 10.285,
 43.17,
 29.22,
 24.98,
 59.2915,
 58.67,
 55.28,
 78.89,
 24.7139,
 75.93,
 33.56,
 48.13,
 32.95,
 35.3,
 66.5385,
 39.73,
 42.05,
 34.24,
 34.55,
 91.51,
 20.3728,
 30.15,
 28.3976,
 102.13,
 18.0,
 7.015,
 29.77,
 59.31,
 27.01,
 14.77,
 56.05,
 35.45,
 76.84,
 85.81,
 24.18,
 18.39,
 8.06,
 27.834,
 35.05,
 40.61,
 26.13,
 50.52,
 10.6812,
 21.58,
 40.25,
 53.7,
 8.0675,
 53.06,
 62.1598,
 32.465,
 52.16,
 82.48,
 45.1178,
 13.84,
 31.6311,
 53.97,
 53.6,
 40.27,
 28.1444,
 58.99,
 25.81,
 48.1024,
 40.34,
 42.63,
 16.6767,
 69.72,
 49.98,
 31.24,
 55.37,
 54.77,
 37.495,
 52.33,
 58.29,
 26.0325,
 32.695,
 40.4,
 49.71,
 29.44,
 24.12,
 65.8,
 27.89,
 16.89,
 21.655,
 30.91,
 7.2125,
 45.88,
 72.3,
 42.12,
 45.59,
 41.24,
 36.02,
 61.475,
 17.42,
 22.7867,
 50.69,
 53.04,
 78.4254,
 8.795,
 38.65,
 42.91,
 33.01,
 39.88,
 17.47,
 27.31,
 58.21,
 60.66,
 18.295,
 79.1,
 44.78,
 32.83,
 74.86,
 16.03,
 21.39,
 32.22,
 31.27,
 46.3,
 36.0,
 38.51,
 25.1467,
 20.01,
 29.725,
 16.6725,
 13.75,
 23.7209,
 23.27,
 59.22,
 54.93,
 24.975,
 49.7142,
 28.6988,
 13.955,
 35.56,
 86.27,
 69.133,
 47.95,
 34.24,
 42.83,
 39.63,
 19.0,
 30.2282,
 90.0,
 6.75,
 16.9603,
 16.145,
 24.02,
 17.64,
 25.44,
 12.605,
 83.51,
 35.78,
 34.55,
 38.72,
 24.78,
 15.6811,
 36.8454,
 53.6,
 14.36,
 50.98,
 38.99,
 53.96,
 60.41,
 90.7973,
 41.7,
 18.135,
 34.7772,
 35.79,
 30.23,
 22.185,
 50.8264,
 35.63,
 24.52,
 68.348,
 23.11,
 64.49,
 46.6305,
 23.67,
 32.77,
 20.89,
 28.8213,
 16.02,
 27.1765,
 33.2,
 29.27,
 51.84,
 45.02,
 23.87,
 23.0568,
 20.01,
 19.685,
 28.62,
 36.8551,
 28.71,
 56.99,
 37.13,
 39.6243,
 15.0321,
 20.7603,
 20.0,
 82.0495,
 5.047,
 24.19]

In [199]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9

In [200]:
df.iloc[-1]

Unnamed: 0                            3234
Date                   2018-05-25 00:00:00
AMAZON.COM                        0.004407
ABBOTT LABORATORIES              -0.002242
AES                               0.001613
                              ...
Unnamed: 485                           NaN
Unnamed: 486                           NaN
Unnamed: 487                           NaN
Unnamed: 488                           NaN
Unnamed: 489                           NaN
Name: 3233, Length: 490, dtype: object

In [203]:
df = pd.read_excel('../Naive_S_P500.xlsx', sheet_name='return')
ret = copy.deepcopy(df.drop(columns=['Unnamed: 0']))
n = 1
ret = ret.iloc[n*20:n*20+60, 1:397]

In [204]:
ret

,AMAZON.COM,ABBOTT LABORATORIES,AES,ABIOMED,INTERNATIONAL BUS.MCHS.,ADVANCED MICRO DEVC.,ADOBE SYSTEMS,ALEXANDRIA RLST.EQTIES.,AIR PRDS.& CHEMS.,ALASKA AIR GROUP,...,DENTSPLY SIRONA,S&P GLOBAL,WELLTOWER,XEROX,HP,DXC TECHNOLOGY,WEC ENERGY GROUP,L3 TECHNOLOGIES,MONSTER BEVERAGE,SBA COMMS.
20,-0.003119,0.004880,0.002350,0.000000,-0.004051,0.009615,0.009611,0.007735,-0.005658,0.047132,...,-0.009637,-0.009943,0.008099,0.023330,-0.003202,-0.005899,0.010656,0.027656,-0.002621,0.058910
21,-0.018919,-0.001158,0.006435,0.018997,0.007841,0.007151,0.019442,0.001472,0.001782,-0.017694,...,-0.001304,0.006250,-0.008642,0.000700,0.001602,0.011570,0.015775,0.024386,0.020963,-0.032088
22,-0.028600,-0.015905,-0.002920,0.003578,-0.008703,-0.025988,-0.028037,-0.011150,-0.014834,0.017694,...,-0.000373,-0.001169,-0.009812,0.003485,-0.010301,0.000193,-0.008574,-0.016028,-0.033230,-0.021979
23,-0.108902,0.001649,0.012783,-0.020750,-0.015633,-0.036747,-0.004835,-0.013013,-0.001150,-0.010705,...,-0.015603,0.010471,-0.008527,-0.008384,-0.011388,-0.017103,-0.012515,-0.005154,0.003232,-0.007273
24,-0.009963,-0.001649,-0.004630,-0.009158,-0.005769,0.041611,0.008130,0.004049,0.033468,-0.022408,...,-0.003797,-0.001544,0.004960,0.016702,-0.009530,-0.005768,0.009401,0.012105,-0.076649,0.019755
25,-0.011395,-0.007333,-0.003486,-0.049987,0.004267,-0.005108,-0.006601,-0.011612,-0.015221,-0.011723,...,0.000570,-0.002127,-0.004132,-0.000692,0.003298,-0.016489,-0.005775,-0.002068,0.000238,-0.025611
26,0.017176,-0.001187,0.004066,0.000967,0.011827,-0.003664,-0.011786,-0.008445,0.004992,0.016245,...,0.002468,0.015751,-0.018947,0.012354,0.052588,0.044221,-0.012139,-0.008685,0.044774,0.006829
27,-0.004727,0.002134,-0.004648,-0.021485,-0.004963,-0.019773,-0.017681,-0.001650,-0.002413,0.016936,...,0.033927,0.018505,-0.003946,-0.022068,-0.012888,-0.025141,-0.015012,-0.000861,-0.006570,-0.007809
28,0.013855,0.007568,0.000000,-0.031080,0.011501,0.000998,0.014842,0.011612,0.004019,0.006002,...,0.006577,-0.000374,0.005351,0.011095,-0.002855,0.021061,-0.012475,0.008083,0.000258,0.018447
29,-0.017282,0.008438,-0.012896,0.010132,-0.011003,-0.028841,-0.013007,-0.006435,-0.002891,-0.006319,...,-0.003283,-0.000936,-0.002250,-0.004147,0.007278,0.013928,0.004259,-0.002198,-0.016873,-0.023851
30,0.010248,0.020794,-0.002363,0.014014,0.008048,0.031829,-0.001572,0.005501,0.015323,0.029359,...,0.017565,0.014506,0.002250,0.003458,0.023354,0.004596,0.002247,0.013599,-0.012933,0.032949
31,0.026063,0.009561,0.011758,0.043760,-0.002964,0.000497,-0.012668,0.001866,0.001582,0.011019,...,-0.009559,0.007542,0.012561,0.004819,-0.025563,0.016873,0.000997,0.006969,0.058276,0.036044
32,-0.002806,0.004746,0.020822,0.034599,0.000742,0.036598,0.024401,0.014803,0.008191,0.000609,...,0.004881,0.007849,0.009112,0.010928,0.071578,0.003754,0.004227,0.003825,0.042816,0.011883
33,0.001021,-0.000452,0.013644,0.023616,-0.002475,-0.034364,-0.020425,0.013568,0.003444,-0.025263,...,0.005754,-0.004373,0.006575,0.002714,0.001469,0.005975,0.009877,-0.012847,0.013804,-0.000909
34,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
35,-0.023233,-0.007927,-0.012500,-0.056314,-0.002605,-0.006967,0.007905,0.005309,-0.009265,-0.017310,...,-0.019738,-0.007515,0.007075,-0.004074,-0.046873,0.008896,-0.000737,-0.008861,0.003179,-0.000455
36,0.011167,-0.002045,-0.004010,0.015080,0.010504,0.018553,0.017175,0.007743,0.010360,0.015748,...,0.006199,0.006785,0.013199,0.023530,0.013145,0.003872,0.008569,0.015966,-0.001444,0.016693
37,-0.021405,-0.010765,-0.001149,0.000000,-0.014237,-0.010100,0.000258,-0.001230,0.005760,0.007472,...,-0.001091,-0.011210,-0.007791,-0.000664,-0.017457,-0.018928,-0.013005,-0.005173,0.058660,-0.010796
38,0.011803,0.011902,0.010292,-0.000936,-0.001248,0.003707,-0.011153,-0.006175,0.001396,-0.017522,...,0.014092,0.003689,-0.008940,0.000664,-0.010871,0.007651,0.004682,0.000482,-0.025184,0.030292
39,-0.008905,0.011311,0.004540,0.014870,0.006595,0.001971,0.021928,-0.002368,0.000620,0.021238,...,0.016017,0.000000,-0.000544,-0.014050,0.042490,0.016776,0.010272,0.018988,-0.004022,-0.006162
40,-0.015110,-0.006093,-0.020596,-0.041437,-0.004849,-0.049196,-0.016466,-0.006455,-0.005905,-0.009626,...,0.006160,-0.022720,-0.007652,0.004033,-0.018122,-0.006604,-0.005612,-0.017060,-0.008118,-0.007089
41,-0.008584,-0.004081,0.011494,0.046957,-0.004246,0.035564,0.012631,0.010848,0.002490,-0.004378,...,-0.003163,0.022167,-0.006330,-0.006058,0.037099,0.005871,0.001711,0.018124,0.022350,0.006206
42,-0.006487,-0.012807,-0.020786,-0.016652,0.000501,0.030961,-0.005909,0.002694,0.001398,-0.021220,...,-0.006003,0.000737,-0.008596,0.015412,0.004106,-0.001095,-0.008093,-0.003196,0.036223,0.012733
43,0.008908,0.007797,0.009869,-0.008431,0.000250,-0.045035,0.006165,-0.001234,-0.008419,-0.027586,...,-0.003193,0.002023,-0.009232,0.005966,-0.027576,-0.005883,-0.008408,-0.002611,-0.001820,-0.034172
44,-0.009451,-0.002289,-0.017483,0.001880,0.000500,-0.003042,-0.016004,0.004367,-0.000940,-0.010253,...,0.001065,0.002935,0.021135,-0.020028,-0.012106,0.009535,-0.013249,-0.013039,0.044638,-0.010438
45,0.001897,-0.003441,0.007030,-0.013233,0.003618,-0.028846,-0.008362,-0.001677,0.011376,0.006957,...,-0.003734,0.006573,-0.007458,0.012731,0.003039,-0.015818,-0.004540,0.007199,-0.025579,-0.025879
46,-0.003255,-0.001148,-0.001753,0.022579,0.010531,-0.031319,-0.008697,0.005580,-0.027330,0.017671,...,-0.000713,-0.000182,0.000554,0.001331,-0.008530,0.000188,0.003029,-0.004793,-0.002004,-0.011300
47,-0.018923,-0.006689,0.011050,-0.022579,-0.001480,-0.024012,-0.009040,0.012168,-0.002072,-0.024628,...,-0.007694,-0.000910,0.009926,-0.002664,0.002444,-0.010621,-0.009877,0.002279,-0.022535,0.004724
48,0.002765,0.016761,-0.004057,0.007583,0.006766,0.011532,-0.006162,0.012782,0.021313,0.008606,...,0.006446,0.000182,0.006290,0.001997,0.007001,0.045234,0.013399,0.008473,0.076396,0.023750
49,-0.000829,0.022733,-0.008163,-0.008535,0.004404,-0.074507,-0.001883,0.004873,-0.001720,-0.001649,...,0.002852,0.008163,-0.005193,0.005972,0.006946,0.002679,-0.001759,-0.003094,0.044722,-0.015770
50,0.019700,0.005104,-0.005283,0.020736,0.011529,0.028702,0.006976,0.012453,0.015526,0.018643,...,0.009035,0.019147,0.009274,0.001981,0.005402,0.015945,0.000503,0.021930,0.000368,0.016690
51,-0.000542,0.001993,0.015767,0.018485,0.006015,0.003708,-0.008593,0.019755,0.007826,0.000648,...,0.004751,0.042168,0.020691,0.009197,0.014566,0.010144,-0.000251,-0.005028,0.021932,0.003213
52,-0.003258,-0.005539,0.018370,0.008208,-0.006135,-0.030060,-0.031505,0.008333,0.005792,0.024313,...,0.002279,0.003393,0.008211,-0.005903,-0.000884,-0.017200,0.007267,0.014082,0.002199,-0.011524
53,-0.021441,0.003991,-0.000569,0.038312,0.005175,-0.003822,0.001391,0.007029,-0.000913,0.023119,...,0.005414,-0.013469,0.010235,0.002629,0.008821,0.007056,0.000998,0.004843,0.017604,0.100900
54,0.006646,-0.020800,-0.024778,0.056916,0.003356,0.005874,0.015718,-0.022396,-0.002436,0.034900,...,0.003304,-0.019586,0.004949,-0.010553,-0.005872,0.003860,-0.005503,-0.004612,-0.006328,0.010008
55,-0.008593,-0.007029,-0.011737,-0.031882,0.002748,0.008456,-0.005487,-0.007401,0.019180,0.006836,...,-0.009594,-0.006674,-0.026324,0.005289,-0.012446,-0.013042,-0.005785,-0.002197,-0.025376,-0.014629
56,0.002225,0.003637,0.006473,0.016068,0.007607,-0.002035,0.007400,0.010241,0.011453,0.027175,...,0.001576,-0.003177,-0.001068,-0.010609,-0.005386,0.006366,0.009790,0.004967,0.001968,0.003782
57,-0.008929,-0.005003,-0.001761,0.071228,-0.014912,0.010995,-0.007951,0.002099,-0.011602,-0.013057,...,0.003494,0.001237,0.007979,0.003993,-0.010847,-0.007076,-0.006014,-0.000806,0.019495,-0.004625
58,-0.005903,-0.000229,-0.009445,0.030772,0.001921,0.038944,0.004394,0.001780,-0.004049,0.002916,...,0.003656,0.013155,-0.009582,-0.003993,0.005140,0.004073,0.005264,-0.010083,-0.011342,0.015887
59,-0.006222,-0.009391,0.004143,-0.005317,-0.003365,-0.022391,-0.019370,-0.010096,-0.004666,0.019323,...,-0.002261,-0.006994,-0.006978,0.002664,-0.001814,0.007048,0.000000,-0.003502,0.067706,0.003313
60,0.012405,-0.011570,-0.006519,-0.020001,-0.007855,-0.035728,-0.007573,0.005797,-0.006967,-0.018159,...,0.004864,-0.006160,-0.003507,-0.014062,-0.031910,-0.028484,0.000750,-0.002808,-0.052013,-0.036628
61,0.017498,-0.000930,0.008289,-0.009368,0.008456,0.005850,0.012033,0.019151,0.015232,0.030366,...,0.002769,0.009489,0.020332,0.018044,0.020065,0.004500,0.009201,0.012926,0.040475,-0.006453
62,0.009590,-0.006546,-0.002361,-0.002356,0.000842,-0.020625,-0.017963,-0.018206,-0.009474,-0.009640,...,0.006374,-0.000350,-0.004512,0.000000,-0.004595,0.000543,-0.002975,-0.008366,-0.005366,0.000431
63,-0.003825,-0.003993,0.008240,0.014052,-0.008813,-0.012884,-0.010248,0.000840,0.015145,0.009922,...,-0.001375,0.008015,0.013476,0.006599,0.010080,-0.001801,-0.007226,0.001049,0.056719,0.009873
64,-0.010734,0.010072,-0.022526,0.000000,0.007129,0.000603,0.021232,-0.021739,-0.010472,-0.017931,...,-0.014900,-0.001911,-0.033902,-0.006599,0.018966,0.030844,0.005238,-0.005142,0.008305,0.004263
65,0.017282,-0.007251,0.026621,0.018434,0.004684,0.007506,0.014185,0.002035,0.000301,0.007724,...,-0.008062,0.005722,-0.001359,-0.011994,0.004764,0.042881,0.004715,-0.003050,0.008929,-0.016295
66,0.015383,0.001643,-0.007618,0.010598,0.008591,0.039589,-0.006094,0.007780,0.018177,-0.007150,...,-0.004409,0.000691,0.006234,0.000000,0.019693,-0.001506,0.005924,-0.004948,-0.003675,-0.017005
67,0.030853,0.004907,-0.009456,0.034052,-0.004286,-0.002303,0.003052,-0.002125,-0.004291,0.004010,...,-0.006561,0.007230,-0.027669,0.002678,-0.007599,-0.005207,-0.016878,-0.011523,0.007635,0.032449
68,-0.037571,-0.018362,-0.024648,-0.007305,-0.015996,-0.029539,0.023273,-0.016627,-0.005650,0.007973,...,0.023386,-0.002232,-0.003060,-0.014815,-0.021638,-0.019208,-0.016404,-0.000120,-0.021975,-0.006835
69,-0.013026,0.002138,0.024054,-0.010317,-0.004618,0.025785,0.014775,-0.006511,-0.010043,-0.013132,...,-0.001739,0.000172,-0.015726,-0.000677,-0.008125,-0.006539,0.007352,0.003698,-0.023619,-0.013811
70,-0.015137,-0.017459,-0.010152,-0.025508,-0.011516,-0.006384,-0.005884,-0.007321,-0.009381,-0.019734,...,0.002434,-0.013149,-0.001416,-0.007496,-0.017060,-0.003638,-0.015015,-0.028498,0.003234,-0.008730
71,0.001939,0.004573,-0.015729,-0.005333,-0.005065,0.030675,-0.008350,-0.009698,0.002126,0.004678,...,-0.002086,0.011601,-0.010257,-0.011697,-0.006478,0.007772,0.001537,0.000490,0.012005,0.014796
72,0.013471,-0.003369,0.013927,0.023406,0.015117,-0.107810,-0.003794,-0.010912,-0.001366,0.026768,...,-0.018443,-0.000689,-0.006320,0.015110,0.008933,-0.000515,-0.011847,0.005251,0.006302,-0.002162
73,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
74,-0.037562,-0.008954,0.008383,-0.017313,-0.004156,-0.038466,0.001628,-0.002466,0.005001,-0.016032,...,-0.009440,-0.003106,0.004313,0.004760,-0.018255,0.009252,-0.005195,-0.001707,0.016345,-0.010007
75,0.028234,0.013286,0.007130,0.053947,0.020249,0.020379,0.012392,0.021430,0.045219,0.023671,...,0.012802,0.013900,0.008571,0.012808,0.044275,0.008319,0.010878,0.022915,0.015453,0.016909
76,0.016674,-0.008192,-0.017319,-0.018882,-0.017558,0.009877,0.005873,0.007333,-0.005941,-0.002257,...,0.027189,-0.020140,0.010753,-0.013486,-0.014740,-0.009855,-0.002321,0.005470,0.023979,0.020426
77,-0.015021,0.013692,0.007203,0.023189,0.001953,-0.005086,0.002924,-0.001419,-0.004224,0.045557,...,0.005487,-0.001218,-0.004513,-0.005447,0.024553,0.016935,0.006947,0.008619,0.001444,0.000421
78,-0.008567,0.002147,-0.007203,-0.005027,-0.004399,0.011092,-0.005856,-0.003501,0.010454,0.018717,...,0.015609,-0.004362,-0.009374,0.010187,-0.025468,-0.011485,-0.004626,-0.000118,0.019041,-0.020847
79,-0.006683,-0.020689,0.006006,-0.029220,0.005496,0.033471,-0.006965,-0.008253,-0.001445,0.014203,...,-0.006587,0.004536,0.000571,-0.055571,-0.001819,-0.003914,0.011780,0.002818,0.031933,0.020005

In [205]:
df = pd.read_excel('../Naive_S_P500.xlsx', sheet_name='price')
price = copy.deepcopy(df.drop(columns=['Unnamed: 0']))
n = 1
price = price.iloc[n:n+1, 1:397]

In [211]:
price.iloc[-1][0]

35.79

In [207]:
[x for x in price]

['AMAZON.COM',
 'ABBOTT LABORATORIES',
 'AES',
 'ABIOMED',
 'INTERNATIONAL BUS.MCHS.',
 'ADVANCED MICRO DEVC.',
 'ADOBE SYSTEMS',
 'ALEXANDRIA RLST.EQTIES.',
 'AIR PRDS.& CHEMS.',
 'ALASKA AIR GROUP',
 'BOSTON PROPERTIES',
 'ALLSTATE',
 'HONEYWELL INTL.',
 'AMGEN',
 'HESS',
 'AMERICAN EXPRESS',
 'AMER.ELEC.PWR.',
 'AFLAC',
 'AMERICAN INTL.GP.',
 'ANALOG DEVICES',
 'ANADARKO PETROLEUM',
 'ALEXION PHARMS.',
 'VALERO ENERGY',
 'APACHE',
 "COMCAST 'A'",
 'ANSYS',
 'APPLE',
 'APPLIED MATS.',
 'ALBEMARLE',
 'ARCHER-DANLS.-MIDL.',
 'PINNACLE WEST CAP.',
 'AMEREN',
 "APARTMENT INV.& MAN.'A'",
 'AUTODESK',
 'AUTOMATIC DATA PROC.',
 'AUTOZONE',
 'AVERY DENNISON',
 'BALL',
 "BERKSHIRE HATHAWAY 'B'",
 'BAXTER INTL.',
 'BECTON DICKINSON',
 'AMETEK',
 'VERIZON COMMUNICATIONS',
 'BEST BUY',
 'SL GREEN REALTY',
 'YUM! BRANDS',
 'FIRSTENERGY',
 'H&R BLOCK',
 'BOEING',
 'ROBERT HALF INTL.',
 'BORGWARNER',
 'BOSTON SCIENTIFIC',
 'CH ROBINSON WWD.',
 'TAKE TWO INTACT.SFTW.',
 'METTLER TOLEDO INTL.',
 'BRISTOL MYERS SQUIBB',
 'AFFILIATED MANAGERS',
 'ONEOK',
 'AVALONBAY COMMNS.',
 'UNITED RENTALS',
 'SEMPRA EN.',
 'FEDEX',
 'VERISIGN',
 "AMPHENOL 'A'",
 "BROWN-FORMAN 'B'",
 'QUANTA SERVICES',
 'CSX',
 "CABOT OIL & GAS 'A'",
 'CAMPBELL SOUP',
 "CONSTELLATION BRANDS 'A'",
 'CARDINAL HEALTH',
 'CATERPILLAR',
 'CELGENE',
 'CITRIX SYS.',
 'CENTURYLINK',
 'CERNER',
 'JP MORGAN CHASE & CO.',
 'CHURCH & DWIGHT CO.',
 'CIGNA',
 'CINCINNATI FINL.',
 'CINTAS',
 'CISCO SYSTEMS',
 'CLOROX',
 'COCA COLA',
 'COLGATE-PALM.',
 "MARRIOTT INTL.'A'",
 'COMERICA',
 'CA',
 'CONAGRA BRANDS',
 'CONSOLIDATED EDISON',
 'CMS ENERGY',
 'COOPER COS.',
 'CORNING',
 'SEALED AIR',
 'CUMMINS',
 'D R HORTON',
 'DANAHER',
 "MOODY'S",
 "COGNIZANT TECH.SLTN.'A'",
 'TARGET',
 'DEERE',
 'MORGAN STANLEY',
 "REPUBLIC SVS.'A'",
 'WALT DISNEY',
 'DOLLAR TREE',
 'DOVER',
 'OMNICOM GROUP',
 'DTE ENERGY',
 'DUKE REALTY',
 'FLOWSERVE',
 'DARDEN RESTAURANTS',
 'EBAY',
 'BANK OF AMERICA',
 'CITIGROUP',
 'EASTMAN CHEMICAL',
 'E*TRADE FINANCIAL',
 'CADENCE DESIGN SYS.',
 "DISH NETWORK 'A'",
 'ECOLAB',
 'PERKINELMER',
 'ELECTRONIC ARTS',
 'EMERSON ELECTRIC',
 'ESSEX PROPERTY TST.',
 'ENTERGY',
 'EOG RES.',
 'EQUIFAX',
 'EQUITY RESD.TST.PROPS. SHBI',
 'EQT',
 "ESTEE LAUDER COS.'A'",
 'EXPEDITOR INTL.OF WASH.',
 'EXXON MOBIL',
 'FMC',
 'NEXTERA ENERGY',
 'FASTENAL',
 'FEDERAL REALTY INV.TST.',
 'FIFTH THIRD BANCORP',
 'M&T BANK',
 'FISERV',
 'FLIR SYSTEMS',
 "MACY'S",
 'FRANKLIN RESOURCES',
 'FREEPORT-MCMORAN',
 'ARTHUR J GALLAGHER',
 'GAP',
 'GENERAL DYNAMICS',
 'GENERAL MILLS',
 'GENUINE PARTS',
 'GILEAD SCIENCES',
 "GARTNER 'A'",
 'GOODYEAR TIRE & RUB.',
 'MCKESSON',
 'NVIDIA',
 'GENERAL ELECTRIC',
 'WW GRAINGER',
 'HALLIBURTON',
 'GOLDMAN SACHS GP.',
 'HARLEY-DAVIDSON',
 'HARRIS',
 'HASBRO',
 'HENRY SCHEIN',
 'HCP',
 'HELMERICH & PAYNE',
 'HERSHEY',
 'F5 NETWORKS',
 'JUNIPER NETWORKS',
 'HOLOGIC',
 'UNUM GROUP',
 'HOME DEPOT',
 'HORMEL FOODS',
 'CENTERPOINT EN.',
 'HUMANA',
 'HUNT JB TRANSPORT SVS.',
 'HUNTINGTON BCSH.',
 'RED HAT',
 'NEKTAR THERAPEUTICS',
 'BIOGEN',
 'ILLINOIS TOOL WORKS',
 'INTUIT',
 'IDEXX LABORATORIES',
 'INTEL',
 'INTL.FLAVORS & FRAG.',
 'INTERNATIONAL PAPER',
 'INTERPUBLIC GROUP',
 'JACOBS ENGR.',
 'INCYTE',
 'JOHNSON & JOHNSON',
 'HARTFORD FINL.SVS.GP.',
 'KLA TENCOR',
 'DEVON ENERGY',
 'KELLOGG',
 'KEYCORP',
 'KIMCO REALTY',
 'KIMBERLY-CLARK',
 'BLACKROCK',
 "KOHL'S",
 'KROGER',
 'LAM RESEARCH',
 'AKAMAI TECHS.',
 'LEGGETT&PLATT',
 "LENNAR 'A'",
 'ELI LILLY',
 'LINCOLN NATIONAL',
 "UNITED PARCEL SER.'B'",
 'AGILENT TECHS.',
 'LOCKHEED MARTIN',
 'LOEWS',
 'CARNIVAL',
 "LOWE'S COMPANIES",
 'DOMINION ENERGY',
 'MACERICH',
 'SCANA',
 'MGM RESORTS INTL.',
 'MCCORMICK & COMPANY NV.',
 'MCDONALDS',
 'EVEREST RE GP.',
 'HOST HOTELS & RESORTS',
 'MARSH & MCLENNAN',
 'MASCO',
 'MARTIN MRTA.MATS.',
 'MATTEL',
 'ACTIVISION BLIZZARD',
 'CVS HEALTH',
 'LABORATORY CORP.OF AM. HDG.',
 'MICROSOFT',
 'MICRON TECHNOLOGY',
 'MID-AMER.APT COMMUNITIES',
 'MICROCHIP TECH.',
 '3M',
 'MOHAWK INDUSTRIES',
 'KANSAS CITY SOUTHERN',
 'XCEL ENERGY',
 'FORD MOTOR',
 'NATIONAL OILWELL VARCO',
 'NETAPP',
 'NEWFIELD EXPLORATION',
 'NEWELL BRANDS',
 'NEWMONT MINING',
 "NIKE 'B'",
 'NOBLE ENERGY',
 'NORDSTROM',
 'NORFOLK SOUTHERN',
 'NISOURCE',
 'NORTHERN TRUST',
 'NORTHROP GRUMMAN',
 'WELLS FARGO & CO',
 'NUCOR',
 'CAPITAL ONE FINL.',
 'OCCIDENTAL PTL.',
 'ORACLE',
 'PACCAR',
 'EXELON',
 'PARKER-HANNIFIN',
 'PAYCHEX',
 'PPL',
 'PEPSICO',
 'PFIZER',
 'CONOCOPHILLIPS',
 'PG&E',
 'PIONEER NTRL.RES.',
 'ALTRIA GROUP',
 'PNC FINL.SVS.GP.',
 'AETNA',
 'PPG INDUSTRIES',
 'PRAXAIR',
 'COSTCO WHOLESALE',
 'T ROWE PRICE GROUP',
 'QUEST DIAGNOSTICS',
 'PROCTER & GAMBLE',
 'PROGRESSIVE OHIO',
 'PUB.SER.ENTER.GP.',
 'PULTEGROUP',
 'QUALCOMM',
 'RAYMOND JAMES FINL.',
 'REALTY INCOME',
 'REGENCY CENTERS',
 'UDR',
 'REGENERON PHARMS.',
 'RESMED',
 'US BANCORP',
 'ROSS STORES',
 'ROPER TECHNOLOGIES',
 'ROCKWELL AUTOMATION',
 'ROYAL CARIBBEAN CRUISES',
 "RAYTHEON 'B'",
 'TRAVELERS COS.',
 'MERCK & COMPANY',
 'SCHLUMBERGER',
 'CHARLES SCHWAB',
 'AMERISOURCEBERGEN',
 'SHERWIN-WILLIAMS',
 'SVB FINANCIAL GROUP',
 'SIMON PROPERTY GROUP',
 'SMITH (AO)',
 'SNAP-ON',
 'EDISON INTL.',
 'SOUTHERN',
 'BB&T',
 'SOUTHWEST AIRLINES',
 'AT&T',
 'CHEVRON',
 'STATE STREET',
 'STARBUCKS',
 'PUBLIC STORAGE',
 'STRYKER',
 'STERICYCLE',
 'SUNTRUST BANKS',
 'SYMANTEC',
 'SYNOPSYS',
 'SYSCO',
 'TEXAS INSTRUMENTS',
 'TEXTRON',
 'THERMO FISHER SCIENTIFIC',
 'TIFFANY & CO',
 'TORCHMARK',
 'TOTAL SYSTEM SERVICES',
 'DAVITA',
 'TRACTOR SUPPLY',
 "TYSON FOODS 'A'",
 'MARATHON OIL',
 'UNION PACIFIC',
 'UNITED TECHNOLOGIES',
 'UNITEDHEALTH GROUP',
 "UNIVERSAL HEALTH SVS.'B'",
 'VARIAN MEDICAL SYSTEMS',
 'VENTAS',
 'V F',
 'VERTEX PHARMS.',
 'VULCAN MATERIALS',
 'VORNADO REALTY TRUST',
 'WALMART',
 'WASTE MANAGEMENT',
 'WATERS',
 'J M SMUCKER',
 'WESTERN DIGITAL',
 'WEYERHAEUSER',
 'WHIRLPOOL',
 'SKYWORKS SOLUTIONS',
 'WILLIAMS',
 'ALLIANT ENERGY CORP.',
 'FOOT LOCKER',
 'CARMAX',
 'XILINX',
 'TJX',
 'ZIONS BANCORP.',
 'REGIONS FINL.NEW',
 "MOLSON COORS BREWING 'B'",
 "VIACOM 'B'",
 "CBS 'B'",
 'PEOPLES UNITED FINANCIAL',
 'BANK OF NEW YORK MELLON',
 'CHUBB',
 'MOSAIC',
 'STANLEY BLACK & DECKER',
 'PVH',
 'PROLOGIS',
 'RALPH LAUREN CL.A',
 'MOTOROLA SOLUTIONS',
 'AON CLASS A',
 'HOLLYFRONTIER',
 'INGERSOLL-RAND',
 'O REILLY AUTOMOTIVE',
 'AMERICAN TOWER',
 'EXPRESS SCRIPTS HOLDING',
 'DUKE ENERGY',
 'EATON',
 'L BRANDS',
 'ARCONIC',
 'ENVISION HEALTHCARE',
 'XL GROUP',
 'BAKER HUGHES A',
 'BOOKING HOLDINGS',
 'ANDEAVOR',
 'EVERGY',
 'JEFFERIES FINANCIAL GROUP',
 'PERRIGO',
 'PENTAIR',
 'QORVO',
 'CROWN CASTLE INTL.',
 'MEDTRONIC',
 'WALGREENS BOOTS ALLIANCE',
 'MYLAN',
 'IRON MOUNTAIN',
 'EVERSOURCE ENERGY',
 'JOHNSON CONTROLS INTL.',
 'ALLERGAN',
 'GGP',
 'DENTSPLY SIRONA',
 'S&P GLOBAL',
 'WELLTOWER',
 'XEROX',
 'HP',
 'DXC TECHNOLOGY',
 'WEC ENERGY GROUP',
 'L3 TECHNOLOGIES',
 'MONSTER BEVERAGE',
 'SBA COMMS.']

In [213]:
[x+y for x, y in zip(price.iloc[-1], [i for i in range(396)])]

[35.79,
 20.6844,
 18.7,
 16.490000000000002,
 86.11,
 37.81,
 43.2,
 97.5,
 71.91069999999999,
 18.572499999999998,
 98.92,
 66.65,
 54.974,
 79.74,
 64.14,
 66.78,
 49.48,
 39.980000000000004,
 1095.062,
 57.39,
 75.63499999999999,
 29.689999999999998,
 85.1209,
 97.58,
 33.4767,
 52.225,
 35.3929,
 44.89,
 51.355000000000004,
 67.21000000000001,
 70.97999999999999,
 81.6,
 63.047,
 75.38,
 69.67269999999999,
 129.26,
 97.88,
 47.8825,
 95.46000000000001,
 60.0785,
 105.28,
 55.8474,
 70.9455,
 99.91,
 145.25,
 62.8324,
 96.03,
 69.25,
 134.1,
 91.50999999999999,
 64.97,
 73.08,
 100.68,
 69.76,
 118.49,
 79.59,
 158.0,
 71.6026,
 165.5,
 93.99000000000001,
 106.13,
 176.67000000000002,
 86.1,
 77.485,
 79.616,
 81.55,
 77.3833,
 73.3812,
 100.05,
 93.01,
 118.6978,
 148.38,
 91.895,
 105.1961,
 112.31,
 85.61,
 118.68,
 86.045,
 117.91329999999999,
 120.8,
 121.84,
 101.28999999999999,
 144.32999999999998,
 103.78,
 112.67,
 118.9999,
 140.61,
 112.51,
 105.32939999999999,
 132.05,
 103.66,
 145.09,
 120.78,
 121.905,
 121.675,
 126.64,
 120.6664,
 168.04000000000002,
 113.845,
 150.8,
 143.24,
 155.2148,
 130.9267,
 129.9074,
 112.6167,
 138.1898,
 149.175,
 147.95,
 143.7,
 127.4,
 146.3637,
 125.7013,
 159.07,
 593.0002,
 141.165,
 380.6997,
 134.32,
 144.6709,
 156.4,
 141.2,
 174.88,
 163.95499999999998,
 229.78,
 193.64,
 161.6,
 163.56,
 170.78,
 163.75,
 146.1,
 174.3,
 194.41,
 146.795,
 171.29,
 156.75,
 202.68,
 174.23,
 250.48000000000002,
 147.4575,
 151.105,
 177.055,
 172.12,
 173.95,
 168.32,
 160.93,
 212.53,
 169.365,
 190.24,
 162.885,
 161.41,
 162.75,
 199.1,
 170.2867,
 185.93,
 230.01,
 194.15,
 320.35,
 207.04,
 199.8551,
 178.82,
 182.435,
 185.0714,
 198.19,
 214.45,
 192.943,
 181.65,
 190.82,
 185.5,
 207.07999999999998,
 176.3425,
 181.08,
 219.2,
 194.98,
 195.37,
 202.67000000000002,
 195.21,
 216.2192,
 227.62,
 204.715,
 199.375,
 197.91,
 215.91,
 218.0787,
 191.5,
 229.335,
 188.21,
 243.32999999999998,
 271.43,
 235.55,
 250.53,
 233.57,
 226.28,
 228.17000000000002,
 248.0893,
 341.14,
 248.12,
 204.82,
 243.13,
 231.02,
 224.03,
 253.4456,
 252.56,
 257.85,
 283.99,
 228.8862,
 281.59000000000003,
 239.7233,
 253.5,
 238.415,
 245.025,
 276.0662,
 249.25,
 254.49,
 246.28,
 247.26,
 307.89,
 234.9227,
 246.68,
 245.4767,
 328.37,
 235.91,
 226.745,
 250.27,
 280.56,
 250.11,
 240.4,
 277.93,
 263.15999999999997,
 312.46,
 305.90999999999997,
 254.0,
 248.45,
 237.96,
 263.5425,
 270.19,
 280.15,
 260.5,
 292.67,
 247.3375,
 261.395,
 277.24,
 296.67,
 249.2089,
 299.75,
 307.6183,
 276.55,
 301.475,
 331.56,
 297.6239,
 262.48,
 281.1866,
 305.65,
 306.8,
 292.38,
 280.2629,
 311.27,
 279.79,
 309.2404,
 296.37,
 302.47,
 275.5054,
 329.59000000000003,
 307.82,
 295.345,
 318.07,
 318.48,
 306.835,
 320.87,
 323.6,
 294.875,
 302.05,
 309.34000000000003,
 323.3,
 302.62,
 295.63,
 337.06,
 303.19,
 290.52,
 298.77,
 308.5,
 286.35,
 329.95,
 359.55,
 324.45,
 328.99,
 326.95,
 319.37,
 354.67,
 304.6,
 311.0099,
 341.83,
 343.47,
 368.8989,
 300.195,
 330.74,
 334.8,
 327.34000000000003,
 337.88,
 313.58,
 323.53,
 359.99,
 363.82,
 320.305,
 379.11,
 348.62,
 336.455,
 379.36,
 322.34,
 328.91,
 338.76,
 344.03,
 355.64,
 348.6,
 348.14,
 338.7689,
 334.19,
 343.585,
 331.8125,
 330.72,
 343.451,
 343.3025,
 384.53,
 371.15999999999997,
 347.365,
 370.4472,
 352.9178,
 340.75,
 364.37,
 418.95,
 398.8165,
 374.54,
 366.51,
 374.99,
 371.18,
 351.96,
 364.7316,
 425.5,
 343.64,
 355.3076,
 354.0,
 362.46,
 357.66,
 367.02,
 354.135,
 423.92,
 379.68,
 381.165,
 385.01,
 371.81,
 363.743,
 385.0186,
 403.52,
 365.68,
 405.44,
 391.39,
 404.68,
 417.06,
 447.4935,
 398.42,
 378.7075,
 393.6335,
 394.92,
 393.74,
 383.1025,
 414.1758,
 402.33,
 389.84,
 446.0661,
 391.15,
 433.93,
 422.6035,
 394.59,
 408.095,
 393.1,
 402.906,
 390.76,
 402.6868,
 408.92,
 407.68,
 427.79,
 421.2,
 401.25,
 403.7256,
 401.79,
 402.1723,
 412.7,
 419.9721,
 415.505,
 444.45,
 423.06,
 425.8843,
 404.9368,
 412.3689,
 411.64,
 474.8002,
 399.8354,
 418.73]